# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/cmake-3.20.0-rc2-linux-x86_64/bin/cmake

# The command to remove a file.
RM = /opt/cmake-3.20.0-rc2-linux-x86_64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/d/PS4/Mira/mira-project/mira_module

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/d/PS4/Mira/mira-project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/cmake-3.20.0-rc2-linux-x86_64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/cmake-3.20.0-rc2-linux-x86_64/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/PS4/Mira/mira-project/CMakeFiles /mnt/d/PS4/Mira/mira-project//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/PS4/Mira/mira-project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mira_module

# Build rule for target.
mira_module: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mira_module
.PHONY : mira_module

# fast build rule for target.
mira_module/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mira_module.dir/build.make CMakeFiles/mira_module.dir/build
.PHONY : mira_module/fast

src/CApi.o: src/CApi.cpp.o
.PHONY : src/CApi.o

# target to build an object file
src/CApi.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mira_module.dir/build.make CMakeFiles/mira_module.dir/src/CApi.cpp.o
.PHONY : src/CApi.cpp.o

src/CApi.i: src/CApi.cpp.i
.PHONY : src/CApi.i

# target to preprocess a source file
src/CApi.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mira_module.dir/build.make CMakeFiles/mira_module.dir/src/CApi.cpp.i
.PHONY : src/CApi.cpp.i

src/CApi.s: src/CApi.cpp.s
.PHONY : src/CApi.s

# target to generate assembly for a file
src/CApi.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mira_module.dir/build.make CMakeFiles/mira_module.dir/src/CApi.cpp.s
.PHONY : src/CApi.cpp.s

src/External/hde64.o: src/External/hde64.cpp.o
.PHONY : src/External/hde64.o

# target to build an object file
src/External/hde64.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mira_module.dir/build.make CMakeFiles/mira_module.dir/src/External/hde64.cpp.o
.PHONY : src/External/hde64.cpp.o

src/External/hde64.i: src/External/hde64.cpp.i
.PHONY : src/External/hde64.i

# target to preprocess a source file
src/External/hde64.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mira_module.dir/build.make CMakeFiles/mira_module.dir/src/External/hde64.cpp.i
.PHONY : src/External/hde64.cpp.i

src/External/hde64.s: src/External/hde64.cpp.s
.PHONY : src/External/hde64.s

# target to generate assembly for a file
src/External/hde64.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mira_module.dir/build.make CMakeFiles/mira_module.dir/src/External/hde64.cpp.s
.PHONY : src/External/hde64.cpp.s

src/Memory/Hook.o: src/Memory/Hook.cpp.o
.PHONY : src/Memory/Hook.o

# target to build an object file
src/Memory/Hook.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mira_module.dir/build.make CMakeFiles/mira_module.dir/src/Memory/Hook.cpp.o
.PHONY : src/Memory/Hook.cpp.o

src/Memory/Hook.i: src/Memory/Hook.cpp.i
.PHONY : src/Memory/Hook.i

# target to preprocess a source file
src/Memory/Hook.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mira_module.dir/build.make CMakeFiles/mira_module.dir/src/Memory/Hook.cpp.i
.PHONY : src/Memory/Hook.cpp.i

src/Memory/Hook.s: src/Memory/Hook.cpp.s
.PHONY : src/Memory/Hook.s

# target to generate assembly for a file
src/Memory/Hook.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mira_module.dir/build.make CMakeFiles/mira_module.dir/src/Memory/Hook.cpp.s
.PHONY : src/Memory/Hook.cpp.s

src/Memory/ProcessMemory.o: src/Memory/ProcessMemory.cpp.o
.PHONY : src/Memory/ProcessMemory.o

# target to build an object file
src/Memory/ProcessMemory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mira_module.dir/build.make CMakeFiles/mira_module.dir/src/Memory/ProcessMemory.cpp.o
.PHONY : src/Memory/ProcessMemory.cpp.o

src/Memory/ProcessMemory.i: src/Memory/ProcessMemory.cpp.i
.PHONY : src/Memory/ProcessMemory.i

# target to preprocess a source file
src/Memory/ProcessMemory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mira_module.dir/build.make CMakeFiles/mira_module.dir/src/Memory/ProcessMemory.cpp.i
.PHONY : src/Memory/ProcessMemory.cpp.i

src/Memory/ProcessMemory.s: src/Memory/ProcessMemory.cpp.s
.PHONY : src/Memory/ProcessMemory.s

# target to generate assembly for a file
src/Memory/ProcessMemory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mira_module.dir/build.make CMakeFiles/mira_module.dir/src/Memory/ProcessMemory.cpp.s
.PHONY : src/Memory/ProcessMemory.cpp.s

src/Memory/Utils.o: src/Memory/Utils.cpp.o
.PHONY : src/Memory/Utils.o

# target to build an object file
src/Memory/Utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mira_module.dir/build.make CMakeFiles/mira_module.dir/src/Memory/Utils.cpp.o
.PHONY : src/Memory/Utils.cpp.o

src/Memory/Utils.i: src/Memory/Utils.cpp.i
.PHONY : src/Memory/Utils.i

# target to preprocess a source file
src/Memory/Utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mira_module.dir/build.make CMakeFiles/mira_module.dir/src/Memory/Utils.cpp.i
.PHONY : src/Memory/Utils.cpp.i

src/Memory/Utils.s: src/Memory/Utils.cpp.s
.PHONY : src/Memory/Utils.s

# target to generate assembly for a file
src/Memory/Utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mira_module.dir/build.make CMakeFiles/mira_module.dir/src/Memory/Utils.cpp.s
.PHONY : src/Memory/Utils.cpp.s

src/System/SystemApi.o: src/System/SystemApi.cpp.o
.PHONY : src/System/SystemApi.o

# target to build an object file
src/System/SystemApi.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mira_module.dir/build.make CMakeFiles/mira_module.dir/src/System/SystemApi.cpp.o
.PHONY : src/System/SystemApi.cpp.o

src/System/SystemApi.i: src/System/SystemApi.cpp.i
.PHONY : src/System/SystemApi.i

# target to preprocess a source file
src/System/SystemApi.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mira_module.dir/build.make CMakeFiles/mira_module.dir/src/System/SystemApi.cpp.i
.PHONY : src/System/SystemApi.cpp.i

src/System/SystemApi.s: src/System/SystemApi.cpp.s
.PHONY : src/System/SystemApi.s

# target to generate assembly for a file
src/System/SystemApi.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mira_module.dir/build.make CMakeFiles/mira_module.dir/src/System/SystemApi.cpp.s
.PHONY : src/System/SystemApi.cpp.s

src/Trainers/Mono/MonoApi.o: src/Trainers/Mono/MonoApi.cpp.o
.PHONY : src/Trainers/Mono/MonoApi.o

# target to build an object file
src/Trainers/Mono/MonoApi.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mira_module.dir/build.make CMakeFiles/mira_module.dir/src/Trainers/Mono/MonoApi.cpp.o
.PHONY : src/Trainers/Mono/MonoApi.cpp.o

src/Trainers/Mono/MonoApi.i: src/Trainers/Mono/MonoApi.cpp.i
.PHONY : src/Trainers/Mono/MonoApi.i

# target to preprocess a source file
src/Trainers/Mono/MonoApi.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mira_module.dir/build.make CMakeFiles/mira_module.dir/src/Trainers/Mono/MonoApi.cpp.i
.PHONY : src/Trainers/Mono/MonoApi.cpp.i

src/Trainers/Mono/MonoApi.s: src/Trainers/Mono/MonoApi.cpp.s
.PHONY : src/Trainers/Mono/MonoApi.s

# target to generate assembly for a file
src/Trainers/Mono/MonoApi.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mira_module.dir/build.make CMakeFiles/mira_module.dir/src/Trainers/Mono/MonoApi.cpp.s
.PHONY : src/Trainers/Mono/MonoApi.cpp.s

src/Utils/Logger.o: src/Utils/Logger.cpp.o
.PHONY : src/Utils/Logger.o

# target to build an object file
src/Utils/Logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mira_module.dir/build.make CMakeFiles/mira_module.dir/src/Utils/Logger.cpp.o
.PHONY : src/Utils/Logger.cpp.o

src/Utils/Logger.i: src/Utils/Logger.cpp.i
.PHONY : src/Utils/Logger.i

# target to preprocess a source file
src/Utils/Logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mira_module.dir/build.make CMakeFiles/mira_module.dir/src/Utils/Logger.cpp.i
.PHONY : src/Utils/Logger.cpp.i

src/Utils/Logger.s: src/Utils/Logger.cpp.s
.PHONY : src/Utils/Logger.s

# target to generate assembly for a file
src/Utils/Logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mira_module.dir/build.make CMakeFiles/mira_module.dir/src/Utils/Logger.cpp.s
.PHONY : src/Utils/Logger.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mira_module.dir/build.make CMakeFiles/mira_module.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mira_module.dir/build.make CMakeFiles/mira_module.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mira_module.dir/build.make CMakeFiles/mira_module.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... mira_module"
	@echo "... src/CApi.o"
	@echo "... src/CApi.i"
	@echo "... src/CApi.s"
	@echo "... src/External/hde64.o"
	@echo "... src/External/hde64.i"
	@echo "... src/External/hde64.s"
	@echo "... src/Memory/Hook.o"
	@echo "... src/Memory/Hook.i"
	@echo "... src/Memory/Hook.s"
	@echo "... src/Memory/ProcessMemory.o"
	@echo "... src/Memory/ProcessMemory.i"
	@echo "... src/Memory/ProcessMemory.s"
	@echo "... src/Memory/Utils.o"
	@echo "... src/Memory/Utils.i"
	@echo "... src/Memory/Utils.s"
	@echo "... src/System/SystemApi.o"
	@echo "... src/System/SystemApi.i"
	@echo "... src/System/SystemApi.s"
	@echo "... src/Trainers/Mono/MonoApi.o"
	@echo "... src/Trainers/Mono/MonoApi.i"
	@echo "... src/Trainers/Mono/MonoApi.s"
	@echo "... src/Utils/Logger.o"
	@echo "... src/Utils/Logger.i"
	@echo "... src/Utils/Logger.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

