/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: rpc.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "rpc.pb-c.h"
void   rpc_header__init
                     (RpcHeader         *message)
{
  static const RpcHeader init_value = RPC_HEADER__INIT;
  *message = init_value;
}
size_t rpc_header__get_packed_size
                     (const RpcHeader *message)
{
  assert(message->base.descriptor == &rpc_header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc_header__pack
                     (const RpcHeader *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc_header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc_header__pack_to_buffer
                     (const RpcHeader *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc_header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpcHeader *
       rpc_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpcHeader *)
     protobuf_c_message_unpack (&rpc_header__descriptor,
                                allocator, len, data);
}
void   rpc_header__free_unpacked
                     (RpcHeader *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc_header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc_transport__init
                     (RpcTransport         *message)
{
  static const RpcTransport init_value = RPC_TRANSPORT__INIT;
  *message = init_value;
}
size_t rpc_transport__get_packed_size
                     (const RpcTransport *message)
{
  assert(message->base.descriptor == &rpc_transport__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc_transport__pack
                     (const RpcTransport *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc_transport__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc_transport__pack_to_buffer
                     (const RpcTransport *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc_transport__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpcTransport *
       rpc_transport__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpcTransport *)
     protobuf_c_message_unpack (&rpc_transport__descriptor,
                                allocator, len, data);
}
void   rpc_transport__free_unpacked
                     (RpcTransport *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc_transport__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor rpc_header__field_descriptors[5] =
{
  {
    "magic",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(RpcHeader, magic),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "category",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(RpcHeader, category),
    &rpc_category__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(RpcHeader, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(RpcHeader, error),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "isRequest",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(RpcHeader, isrequest),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc_header__field_indices_by_name[] = {
  1,   /* field[1] = category */
  3,   /* field[3] = error */
  4,   /* field[4] = isRequest */
  0,   /* field[0] = magic */
  2,   /* field[2] = type */
};
static const ProtobufCIntRange rpc_header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor rpc_header__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RpcHeader",
  "RpcHeader",
  "RpcHeader",
  "",
  sizeof(RpcHeader),
  5,
  rpc_header__field_descriptors,
  rpc_header__field_indices_by_name,
  1,  rpc_header__number_ranges,
  (ProtobufCMessageInit) rpc_header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpc_transport__field_descriptors[3] =
{
  {
    "header",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(RpcTransport, header),
    &rpc_header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dataLength",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(RpcTransport, datalength),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RpcTransport, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc_transport__field_indices_by_name[] = {
  2,   /* field[2] = data */
  1,   /* field[1] = dataLength */
  0,   /* field[0] = header */
};
static const ProtobufCIntRange rpc_transport__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor rpc_transport__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RpcTransport",
  "RpcTransport",
  "RpcTransport",
  "",
  sizeof(RpcTransport),
  3,
  rpc_transport__field_descriptors,
  rpc_transport__field_indices_by_name,
  1,  rpc_transport__number_ranges,
  (ProtobufCMessageInit) rpc_transport__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue rpc_category__enum_values_by_number[7] =
{
  { "NONE", "RPC_CATEGORY__NONE", 0 },
  { "SYSTEM", "RPC_CATEGORY__SYSTEM", 1 },
  { "LOG", "RPC_CATEGORY__LOG", 2 },
  { "DEBUG", "RPC_CATEGORY__DEBUG", 3 },
  { "FILE", "RPC_CATEGORY__FILE", 4 },
  { "COMMAND", "RPC_CATEGORY__COMMAND", 5 },
  { "MAX", "RPC_CATEGORY__MAX", 6 },
};
static const ProtobufCIntRange rpc_category__value_ranges[] = {
{0, 0},{0, 7}
};
static const ProtobufCEnumValueIndex rpc_category__enum_values_by_name[7] =
{
  { "COMMAND", 5 },
  { "DEBUG", 3 },
  { "FILE", 4 },
  { "LOG", 2 },
  { "MAX", 6 },
  { "NONE", 0 },
  { "SYSTEM", 1 },
};
const ProtobufCEnumDescriptor rpc_category__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "RpcCategory",
  "RpcCategory",
  "RpcCategory",
  "",
  7,
  rpc_category__enum_values_by_number,
  7,
  rpc_category__enum_values_by_name,
  1,
  rpc_category__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
