/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: external/debugger.proto */

#ifndef PROTOBUF_C_external_2fdebugger_2eproto__INCLUDED
#define PROTOBUF_C_external_2fdebugger_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "debugger_structs.pb-c.h"

typedef struct _DbgGetProcessListResponse DbgGetProcessListResponse;
typedef struct _DbgReadProcessMemoryRequest DbgReadProcessMemoryRequest;
typedef struct _DbgReadProcessMemoryResponse DbgReadProcessMemoryResponse;
typedef struct _DbgWriteProcessMemoryRequest DbgWriteProcessMemoryRequest;
typedef struct _DbgProtectProcessMemoryRequest DbgProtectProcessMemoryRequest;
typedef struct _DbgScanProcessMemoryRequest DbgScanProcessMemoryRequest;
typedef struct _DbgGetProcessInfoRequest DbgGetProcessInfoRequest;
typedef struct _DbgAllocateProcessMemoryRequest DbgAllocateProcessMemoryRequest;
typedef struct _DbgAllocateProcessMemoryResponse DbgAllocateProcessMemoryResponse;
typedef struct _DbgFreeProcessMemoryRequest DbgFreeProcessMemoryRequest;
typedef struct _DbgGetProcessMapsRequest DbgGetProcessMapsRequest;
typedef struct _DbgAttachRequest DbgAttachRequest;
typedef struct _DbgDetachRequest DbgDetachRequest;
typedef struct _DbgBreakpointRequest DbgBreakpointRequest;
typedef struct _DbgBreakpointResponse DbgBreakpointResponse;
typedef struct _DbgWatchpointRequest DbgWatchpointRequest;
typedef struct _DbgWatchpointResponse DbgWatchpointResponse;
typedef struct _DbgGetProcessThreadsRequest DbgGetProcessThreadsRequest;
typedef struct _DbgGetProcessThreadsResponse DbgGetProcessThreadsResponse;
typedef struct _DbgSignalProcessRequest DbgSignalProcessRequest;
typedef struct _DbgGetRegistersRequest DbgGetRegistersRequest;
typedef struct _DbgGetRegistersResponse DbgGetRegistersResponse;
typedef struct _DbgSetRegistersRequest DbgSetRegistersRequest;
typedef struct _DbgGetThreadInfoRequest DbgGetThreadInfoRequest;
typedef struct _DbgThreadSinglestepRequest DbgThreadSinglestepRequest;
typedef struct _DbgGetKernelInfoResponse DbgGetKernelInfoResponse;
typedef struct _DbgReadKernelMemoryRequest DbgReadKernelMemoryRequest;
typedef struct _DbgReadKernelMemoryResponse DbgReadKernelMemoryResponse;
typedef struct _DbgWriteKernelMemoryRequest DbgWriteKernelMemoryRequest;
typedef struct _DbgCommandRequest DbgCommandRequest;


/* --- enums --- */

typedef enum _DbgCommandRequest__DbgCommands {
  DBG_COMMAND_REQUEST__DBG_COMMANDS__DBG_NONE = 0,
  DBG_COMMAND_REQUEST__DBG_COMMANDS__DBG_REBOOT = 1,
  DBG_COMMAND_REQUEST__DBG_COMMANDS__DBG_SHUTDOWN = 2,
  DBG_COMMAND_REQUEST__DBG_COMMANDS__DBG_PRINT = 3,
  DBG_COMMAND_REQUEST__DBG_COMMANDS__DBG_NOTIFY = 4,
  DBG_COMMAND_REQUEST__DBG_COMMANDS__DBG_INFO = 5
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(DBG_COMMAND_REQUEST__DBG_COMMANDS)
} DbgCommandRequest__DbgCommands;
typedef enum _DbgBreakpointType {
  DBG_BREAKPOINT_TYPE__BP_NONE = 0,
  DBG_BREAKPOINT_TYPE__BP_SOFTWARE = 1,
  DBG_BREAKPOINT_TYPE__BP_HARDWARE = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(DBG_BREAKPOINT_TYPE)
} DbgBreakpointType;

/* --- messages --- */

/*
 * Has no request payload
 */
struct  _DbgGetProcessListResponse
{
  ProtobufCMessage base;
  size_t n_processes;
  DbgProcessLimited **processes;
};
#define DBG_GET_PROCESS_LIST_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbg_get_process_list_response__descriptor) \
    , 0,NULL }


struct  _DbgReadProcessMemoryRequest
{
  ProtobufCMessage base;
  uint64_t address;
  uint32_t size;
};
#define DBG_READ_PROCESS_MEMORY_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbg_read_process_memory_request__descriptor) \
    , 0, 0 }


struct  _DbgReadProcessMemoryResponse
{
  ProtobufCMessage base;
  ProtobufCBinaryData data;
};
#define DBG_READ_PROCESS_MEMORY_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbg_read_process_memory_response__descriptor) \
    , {0,NULL} }


struct  _DbgWriteProcessMemoryRequest
{
  ProtobufCMessage base;
  uint64_t address;
  /*
   * Size is inside here
   */
  ProtobufCBinaryData data;
};
#define DBG_WRITE_PROCESS_MEMORY_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbg_write_process_memory_request__descriptor) \
    , 0, {0,NULL} }


struct  _DbgProtectProcessMemoryRequest
{
  ProtobufCMessage base;
  uint64_t address;
  uint64_t length;
  int32_t protection;
};
#define DBG_PROTECT_PROCESS_MEMORY_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbg_protect_process_memory_request__descriptor) \
    , 0, 0, 0 }


struct  _DbgScanProcessMemoryRequest
{
  ProtobufCMessage base;
};
#define DBG_SCAN_PROCESS_MEMORY_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbg_scan_process_memory_request__descriptor) \
     }


struct  _DbgGetProcessInfoRequest
{
  ProtobufCMessage base;
  int32_t processid;
};
#define DBG_GET_PROCESS_INFO_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbg_get_process_info_request__descriptor) \
    , 0 }


struct  _DbgAllocateProcessMemoryRequest
{
  ProtobufCMessage base;
  uint32_t size;
};
#define DBG_ALLOCATE_PROCESS_MEMORY_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbg_allocate_process_memory_request__descriptor) \
    , 0 }


struct  _DbgAllocateProcessMemoryResponse
{
  ProtobufCMessage base;
  uint64_t address;
  uint32_t size;
};
#define DBG_ALLOCATE_PROCESS_MEMORY_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbg_allocate_process_memory_response__descriptor) \
    , 0, 0 }


struct  _DbgFreeProcessMemoryRequest
{
  ProtobufCMessage base;
  uint64_t address;
  uint32_t size;
};
#define DBG_FREE_PROCESS_MEMORY_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbg_free_process_memory_request__descriptor) \
    , 0, 0 }


struct  _DbgGetProcessMapsRequest
{
  ProtobufCMessage base;
  int32_t processid;
};
#define DBG_GET_PROCESS_MAPS_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbg_get_process_maps_request__descriptor) \
    , 0 }


struct  _DbgAttachRequest
{
  ProtobufCMessage base;
  int32_t processid;
};
#define DBG_ATTACH_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbg_attach_request__descriptor) \
    , 0 }


struct  _DbgDetachRequest
{
  ProtobufCMessage base;
  protobuf_c_boolean force;
};
#define DBG_DETACH_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbg_detach_request__descriptor) \
    , 0 }


struct  _DbgBreakpointRequest
{
  ProtobufCMessage base;
  protobuf_c_boolean enabled;
  uint64_t address;
  uint32_t original;
  DbgBreakpointType breakpointtype;
};
#define DBG_BREAKPOINT_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbg_breakpoint_request__descriptor) \
    , 0, 0, 0, DBG_BREAKPOINT_TYPE__BP_NONE }


struct  _DbgBreakpointResponse
{
  ProtobufCMessage base;
  uint64_t breakpointhandle;
};
#define DBG_BREAKPOINT_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbg_breakpoint_response__descriptor) \
    , 0 }


struct  _DbgWatchpointRequest
{
  ProtobufCMessage base;
  protobuf_c_boolean enabled;
  uint64_t address;
  uint32_t breakpointtype;
  uint32_t length;
};
#define DBG_WATCHPOINT_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbg_watchpoint_request__descriptor) \
    , 0, 0, 0, 0 }


struct  _DbgWatchpointResponse
{
  ProtobufCMessage base;
  uint64_t watchpointhandle;
};
#define DBG_WATCHPOINT_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbg_watchpoint_response__descriptor) \
    , 0 }


struct  _DbgGetProcessThreadsRequest
{
  ProtobufCMessage base;
  int32_t processid;
};
#define DBG_GET_PROCESS_THREADS_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbg_get_process_threads_request__descriptor) \
    , 0 }


struct  _DbgGetProcessThreadsResponse
{
  ProtobufCMessage base;
  size_t n_threads;
  DbgThreadLimited **threads;
};
#define DBG_GET_PROCESS_THREADS_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbg_get_process_threads_response__descriptor) \
    , 0,NULL }


struct  _DbgSignalProcessRequest
{
  ProtobufCMessage base;
  int32_t signal;
};
#define DBG_SIGNAL_PROCESS_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbg_signal_process_request__descriptor) \
    , 0 }


struct  _DbgGetRegistersRequest
{
  ProtobufCMessage base;
  int32_t threadid;
};
#define DBG_GET_REGISTERS_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbg_get_registers_request__descriptor) \
    , 0 }


struct  _DbgGetRegistersResponse
{
  ProtobufCMessage base;
  DbgGpRegisters *gpregisters;
  DbgFpRegisters *fpregisters;
  DbgDbRegisters *dbregisters;
};
#define DBG_GET_REGISTERS_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbg_get_registers_response__descriptor) \
    , NULL, NULL, NULL }


struct  _DbgSetRegistersRequest
{
  ProtobufCMessage base;
  int32_t threadid;
  DbgGpRegisters *gpregisters;
  DbgFpRegisters *fpregisters;
  DbgDbRegisters *dbregisters;
};
#define DBG_SET_REGISTERS_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbg_set_registers_request__descriptor) \
    , 0, NULL, NULL, NULL }


struct  _DbgGetThreadInfoRequest
{
  ProtobufCMessage base;
  int32_t threadid;
};
#define DBG_GET_THREAD_INFO_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbg_get_thread_info_request__descriptor) \
    , 0 }


struct  _DbgThreadSinglestepRequest
{
  ProtobufCMessage base;
  int32_t processid;
  int32_t threadid;
};
#define DBG_THREAD_SINGLESTEP_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbg_thread_singlestep_request__descriptor) \
    , 0, 0 }


struct  _DbgGetKernelInfoResponse
{
  ProtobufCMessage base;
  uint64_t version;
  /*
   * len 140?
   */
  ProtobufCBinaryData gloablconfigdata;
};
#define DBG_GET_KERNEL_INFO_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbg_get_kernel_info_response__descriptor) \
    , 0, {0,NULL} }


struct  _DbgReadKernelMemoryRequest
{
  ProtobufCMessage base;
  uint64_t address;
  uint64_t size;
};
#define DBG_READ_KERNEL_MEMORY_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbg_read_kernel_memory_request__descriptor) \
    , 0, 0 }


struct  _DbgReadKernelMemoryResponse
{
  ProtobufCMessage base;
  ProtobufCBinaryData data;
};
#define DBG_READ_KERNEL_MEMORY_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbg_read_kernel_memory_response__descriptor) \
    , {0,NULL} }


struct  _DbgWriteKernelMemoryRequest
{
  ProtobufCMessage base;
  uint64_t address;
  ProtobufCBinaryData data;
};
#define DBG_WRITE_KERNEL_MEMORY_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbg_write_kernel_memory_request__descriptor) \
    , 0, {0,NULL} }


struct  _DbgCommandRequest
{
  ProtobufCMessage base;
  DbgCommandRequest__DbgCommands command;
};
#define DBG_COMMAND_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbg_command_request__descriptor) \
    , DBG_COMMAND_REQUEST__DBG_COMMANDS__DBG_NONE }


/* DbgGetProcessListResponse methods */
void   dbg_get_process_list_response__init
                     (DbgGetProcessListResponse         *message);
size_t dbg_get_process_list_response__get_packed_size
                     (const DbgGetProcessListResponse   *message);
size_t dbg_get_process_list_response__pack
                     (const DbgGetProcessListResponse   *message,
                      uint8_t             *out);
size_t dbg_get_process_list_response__pack_to_buffer
                     (const DbgGetProcessListResponse   *message,
                      ProtobufCBuffer     *buffer);
DbgGetProcessListResponse *
       dbg_get_process_list_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbg_get_process_list_response__free_unpacked
                     (DbgGetProcessListResponse *message,
                      ProtobufCAllocator *allocator);
/* DbgReadProcessMemoryRequest methods */
void   dbg_read_process_memory_request__init
                     (DbgReadProcessMemoryRequest         *message);
size_t dbg_read_process_memory_request__get_packed_size
                     (const DbgReadProcessMemoryRequest   *message);
size_t dbg_read_process_memory_request__pack
                     (const DbgReadProcessMemoryRequest   *message,
                      uint8_t             *out);
size_t dbg_read_process_memory_request__pack_to_buffer
                     (const DbgReadProcessMemoryRequest   *message,
                      ProtobufCBuffer     *buffer);
DbgReadProcessMemoryRequest *
       dbg_read_process_memory_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbg_read_process_memory_request__free_unpacked
                     (DbgReadProcessMemoryRequest *message,
                      ProtobufCAllocator *allocator);
/* DbgReadProcessMemoryResponse methods */
void   dbg_read_process_memory_response__init
                     (DbgReadProcessMemoryResponse         *message);
size_t dbg_read_process_memory_response__get_packed_size
                     (const DbgReadProcessMemoryResponse   *message);
size_t dbg_read_process_memory_response__pack
                     (const DbgReadProcessMemoryResponse   *message,
                      uint8_t             *out);
size_t dbg_read_process_memory_response__pack_to_buffer
                     (const DbgReadProcessMemoryResponse   *message,
                      ProtobufCBuffer     *buffer);
DbgReadProcessMemoryResponse *
       dbg_read_process_memory_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbg_read_process_memory_response__free_unpacked
                     (DbgReadProcessMemoryResponse *message,
                      ProtobufCAllocator *allocator);
/* DbgWriteProcessMemoryRequest methods */
void   dbg_write_process_memory_request__init
                     (DbgWriteProcessMemoryRequest         *message);
size_t dbg_write_process_memory_request__get_packed_size
                     (const DbgWriteProcessMemoryRequest   *message);
size_t dbg_write_process_memory_request__pack
                     (const DbgWriteProcessMemoryRequest   *message,
                      uint8_t             *out);
size_t dbg_write_process_memory_request__pack_to_buffer
                     (const DbgWriteProcessMemoryRequest   *message,
                      ProtobufCBuffer     *buffer);
DbgWriteProcessMemoryRequest *
       dbg_write_process_memory_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbg_write_process_memory_request__free_unpacked
                     (DbgWriteProcessMemoryRequest *message,
                      ProtobufCAllocator *allocator);
/* DbgProtectProcessMemoryRequest methods */
void   dbg_protect_process_memory_request__init
                     (DbgProtectProcessMemoryRequest         *message);
size_t dbg_protect_process_memory_request__get_packed_size
                     (const DbgProtectProcessMemoryRequest   *message);
size_t dbg_protect_process_memory_request__pack
                     (const DbgProtectProcessMemoryRequest   *message,
                      uint8_t             *out);
size_t dbg_protect_process_memory_request__pack_to_buffer
                     (const DbgProtectProcessMemoryRequest   *message,
                      ProtobufCBuffer     *buffer);
DbgProtectProcessMemoryRequest *
       dbg_protect_process_memory_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbg_protect_process_memory_request__free_unpacked
                     (DbgProtectProcessMemoryRequest *message,
                      ProtobufCAllocator *allocator);
/* DbgScanProcessMemoryRequest methods */
void   dbg_scan_process_memory_request__init
                     (DbgScanProcessMemoryRequest         *message);
size_t dbg_scan_process_memory_request__get_packed_size
                     (const DbgScanProcessMemoryRequest   *message);
size_t dbg_scan_process_memory_request__pack
                     (const DbgScanProcessMemoryRequest   *message,
                      uint8_t             *out);
size_t dbg_scan_process_memory_request__pack_to_buffer
                     (const DbgScanProcessMemoryRequest   *message,
                      ProtobufCBuffer     *buffer);
DbgScanProcessMemoryRequest *
       dbg_scan_process_memory_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbg_scan_process_memory_request__free_unpacked
                     (DbgScanProcessMemoryRequest *message,
                      ProtobufCAllocator *allocator);
/* DbgGetProcessInfoRequest methods */
void   dbg_get_process_info_request__init
                     (DbgGetProcessInfoRequest         *message);
size_t dbg_get_process_info_request__get_packed_size
                     (const DbgGetProcessInfoRequest   *message);
size_t dbg_get_process_info_request__pack
                     (const DbgGetProcessInfoRequest   *message,
                      uint8_t             *out);
size_t dbg_get_process_info_request__pack_to_buffer
                     (const DbgGetProcessInfoRequest   *message,
                      ProtobufCBuffer     *buffer);
DbgGetProcessInfoRequest *
       dbg_get_process_info_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbg_get_process_info_request__free_unpacked
                     (DbgGetProcessInfoRequest *message,
                      ProtobufCAllocator *allocator);
/* DbgAllocateProcessMemoryRequest methods */
void   dbg_allocate_process_memory_request__init
                     (DbgAllocateProcessMemoryRequest         *message);
size_t dbg_allocate_process_memory_request__get_packed_size
                     (const DbgAllocateProcessMemoryRequest   *message);
size_t dbg_allocate_process_memory_request__pack
                     (const DbgAllocateProcessMemoryRequest   *message,
                      uint8_t             *out);
size_t dbg_allocate_process_memory_request__pack_to_buffer
                     (const DbgAllocateProcessMemoryRequest   *message,
                      ProtobufCBuffer     *buffer);
DbgAllocateProcessMemoryRequest *
       dbg_allocate_process_memory_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbg_allocate_process_memory_request__free_unpacked
                     (DbgAllocateProcessMemoryRequest *message,
                      ProtobufCAllocator *allocator);
/* DbgAllocateProcessMemoryResponse methods */
void   dbg_allocate_process_memory_response__init
                     (DbgAllocateProcessMemoryResponse         *message);
size_t dbg_allocate_process_memory_response__get_packed_size
                     (const DbgAllocateProcessMemoryResponse   *message);
size_t dbg_allocate_process_memory_response__pack
                     (const DbgAllocateProcessMemoryResponse   *message,
                      uint8_t             *out);
size_t dbg_allocate_process_memory_response__pack_to_buffer
                     (const DbgAllocateProcessMemoryResponse   *message,
                      ProtobufCBuffer     *buffer);
DbgAllocateProcessMemoryResponse *
       dbg_allocate_process_memory_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbg_allocate_process_memory_response__free_unpacked
                     (DbgAllocateProcessMemoryResponse *message,
                      ProtobufCAllocator *allocator);
/* DbgFreeProcessMemoryRequest methods */
void   dbg_free_process_memory_request__init
                     (DbgFreeProcessMemoryRequest         *message);
size_t dbg_free_process_memory_request__get_packed_size
                     (const DbgFreeProcessMemoryRequest   *message);
size_t dbg_free_process_memory_request__pack
                     (const DbgFreeProcessMemoryRequest   *message,
                      uint8_t             *out);
size_t dbg_free_process_memory_request__pack_to_buffer
                     (const DbgFreeProcessMemoryRequest   *message,
                      ProtobufCBuffer     *buffer);
DbgFreeProcessMemoryRequest *
       dbg_free_process_memory_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbg_free_process_memory_request__free_unpacked
                     (DbgFreeProcessMemoryRequest *message,
                      ProtobufCAllocator *allocator);
/* DbgGetProcessMapsRequest methods */
void   dbg_get_process_maps_request__init
                     (DbgGetProcessMapsRequest         *message);
size_t dbg_get_process_maps_request__get_packed_size
                     (const DbgGetProcessMapsRequest   *message);
size_t dbg_get_process_maps_request__pack
                     (const DbgGetProcessMapsRequest   *message,
                      uint8_t             *out);
size_t dbg_get_process_maps_request__pack_to_buffer
                     (const DbgGetProcessMapsRequest   *message,
                      ProtobufCBuffer     *buffer);
DbgGetProcessMapsRequest *
       dbg_get_process_maps_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbg_get_process_maps_request__free_unpacked
                     (DbgGetProcessMapsRequest *message,
                      ProtobufCAllocator *allocator);
/* DbgAttachRequest methods */
void   dbg_attach_request__init
                     (DbgAttachRequest         *message);
size_t dbg_attach_request__get_packed_size
                     (const DbgAttachRequest   *message);
size_t dbg_attach_request__pack
                     (const DbgAttachRequest   *message,
                      uint8_t             *out);
size_t dbg_attach_request__pack_to_buffer
                     (const DbgAttachRequest   *message,
                      ProtobufCBuffer     *buffer);
DbgAttachRequest *
       dbg_attach_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbg_attach_request__free_unpacked
                     (DbgAttachRequest *message,
                      ProtobufCAllocator *allocator);
/* DbgDetachRequest methods */
void   dbg_detach_request__init
                     (DbgDetachRequest         *message);
size_t dbg_detach_request__get_packed_size
                     (const DbgDetachRequest   *message);
size_t dbg_detach_request__pack
                     (const DbgDetachRequest   *message,
                      uint8_t             *out);
size_t dbg_detach_request__pack_to_buffer
                     (const DbgDetachRequest   *message,
                      ProtobufCBuffer     *buffer);
DbgDetachRequest *
       dbg_detach_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbg_detach_request__free_unpacked
                     (DbgDetachRequest *message,
                      ProtobufCAllocator *allocator);
/* DbgBreakpointRequest methods */
void   dbg_breakpoint_request__init
                     (DbgBreakpointRequest         *message);
size_t dbg_breakpoint_request__get_packed_size
                     (const DbgBreakpointRequest   *message);
size_t dbg_breakpoint_request__pack
                     (const DbgBreakpointRequest   *message,
                      uint8_t             *out);
size_t dbg_breakpoint_request__pack_to_buffer
                     (const DbgBreakpointRequest   *message,
                      ProtobufCBuffer     *buffer);
DbgBreakpointRequest *
       dbg_breakpoint_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbg_breakpoint_request__free_unpacked
                     (DbgBreakpointRequest *message,
                      ProtobufCAllocator *allocator);
/* DbgBreakpointResponse methods */
void   dbg_breakpoint_response__init
                     (DbgBreakpointResponse         *message);
size_t dbg_breakpoint_response__get_packed_size
                     (const DbgBreakpointResponse   *message);
size_t dbg_breakpoint_response__pack
                     (const DbgBreakpointResponse   *message,
                      uint8_t             *out);
size_t dbg_breakpoint_response__pack_to_buffer
                     (const DbgBreakpointResponse   *message,
                      ProtobufCBuffer     *buffer);
DbgBreakpointResponse *
       dbg_breakpoint_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbg_breakpoint_response__free_unpacked
                     (DbgBreakpointResponse *message,
                      ProtobufCAllocator *allocator);
/* DbgWatchpointRequest methods */
void   dbg_watchpoint_request__init
                     (DbgWatchpointRequest         *message);
size_t dbg_watchpoint_request__get_packed_size
                     (const DbgWatchpointRequest   *message);
size_t dbg_watchpoint_request__pack
                     (const DbgWatchpointRequest   *message,
                      uint8_t             *out);
size_t dbg_watchpoint_request__pack_to_buffer
                     (const DbgWatchpointRequest   *message,
                      ProtobufCBuffer     *buffer);
DbgWatchpointRequest *
       dbg_watchpoint_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbg_watchpoint_request__free_unpacked
                     (DbgWatchpointRequest *message,
                      ProtobufCAllocator *allocator);
/* DbgWatchpointResponse methods */
void   dbg_watchpoint_response__init
                     (DbgWatchpointResponse         *message);
size_t dbg_watchpoint_response__get_packed_size
                     (const DbgWatchpointResponse   *message);
size_t dbg_watchpoint_response__pack
                     (const DbgWatchpointResponse   *message,
                      uint8_t             *out);
size_t dbg_watchpoint_response__pack_to_buffer
                     (const DbgWatchpointResponse   *message,
                      ProtobufCBuffer     *buffer);
DbgWatchpointResponse *
       dbg_watchpoint_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbg_watchpoint_response__free_unpacked
                     (DbgWatchpointResponse *message,
                      ProtobufCAllocator *allocator);
/* DbgGetProcessThreadsRequest methods */
void   dbg_get_process_threads_request__init
                     (DbgGetProcessThreadsRequest         *message);
size_t dbg_get_process_threads_request__get_packed_size
                     (const DbgGetProcessThreadsRequest   *message);
size_t dbg_get_process_threads_request__pack
                     (const DbgGetProcessThreadsRequest   *message,
                      uint8_t             *out);
size_t dbg_get_process_threads_request__pack_to_buffer
                     (const DbgGetProcessThreadsRequest   *message,
                      ProtobufCBuffer     *buffer);
DbgGetProcessThreadsRequest *
       dbg_get_process_threads_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbg_get_process_threads_request__free_unpacked
                     (DbgGetProcessThreadsRequest *message,
                      ProtobufCAllocator *allocator);
/* DbgGetProcessThreadsResponse methods */
void   dbg_get_process_threads_response__init
                     (DbgGetProcessThreadsResponse         *message);
size_t dbg_get_process_threads_response__get_packed_size
                     (const DbgGetProcessThreadsResponse   *message);
size_t dbg_get_process_threads_response__pack
                     (const DbgGetProcessThreadsResponse   *message,
                      uint8_t             *out);
size_t dbg_get_process_threads_response__pack_to_buffer
                     (const DbgGetProcessThreadsResponse   *message,
                      ProtobufCBuffer     *buffer);
DbgGetProcessThreadsResponse *
       dbg_get_process_threads_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbg_get_process_threads_response__free_unpacked
                     (DbgGetProcessThreadsResponse *message,
                      ProtobufCAllocator *allocator);
/* DbgSignalProcessRequest methods */
void   dbg_signal_process_request__init
                     (DbgSignalProcessRequest         *message);
size_t dbg_signal_process_request__get_packed_size
                     (const DbgSignalProcessRequest   *message);
size_t dbg_signal_process_request__pack
                     (const DbgSignalProcessRequest   *message,
                      uint8_t             *out);
size_t dbg_signal_process_request__pack_to_buffer
                     (const DbgSignalProcessRequest   *message,
                      ProtobufCBuffer     *buffer);
DbgSignalProcessRequest *
       dbg_signal_process_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbg_signal_process_request__free_unpacked
                     (DbgSignalProcessRequest *message,
                      ProtobufCAllocator *allocator);
/* DbgGetRegistersRequest methods */
void   dbg_get_registers_request__init
                     (DbgGetRegistersRequest         *message);
size_t dbg_get_registers_request__get_packed_size
                     (const DbgGetRegistersRequest   *message);
size_t dbg_get_registers_request__pack
                     (const DbgGetRegistersRequest   *message,
                      uint8_t             *out);
size_t dbg_get_registers_request__pack_to_buffer
                     (const DbgGetRegistersRequest   *message,
                      ProtobufCBuffer     *buffer);
DbgGetRegistersRequest *
       dbg_get_registers_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbg_get_registers_request__free_unpacked
                     (DbgGetRegistersRequest *message,
                      ProtobufCAllocator *allocator);
/* DbgGetRegistersResponse methods */
void   dbg_get_registers_response__init
                     (DbgGetRegistersResponse         *message);
size_t dbg_get_registers_response__get_packed_size
                     (const DbgGetRegistersResponse   *message);
size_t dbg_get_registers_response__pack
                     (const DbgGetRegistersResponse   *message,
                      uint8_t             *out);
size_t dbg_get_registers_response__pack_to_buffer
                     (const DbgGetRegistersResponse   *message,
                      ProtobufCBuffer     *buffer);
DbgGetRegistersResponse *
       dbg_get_registers_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbg_get_registers_response__free_unpacked
                     (DbgGetRegistersResponse *message,
                      ProtobufCAllocator *allocator);
/* DbgSetRegistersRequest methods */
void   dbg_set_registers_request__init
                     (DbgSetRegistersRequest         *message);
size_t dbg_set_registers_request__get_packed_size
                     (const DbgSetRegistersRequest   *message);
size_t dbg_set_registers_request__pack
                     (const DbgSetRegistersRequest   *message,
                      uint8_t             *out);
size_t dbg_set_registers_request__pack_to_buffer
                     (const DbgSetRegistersRequest   *message,
                      ProtobufCBuffer     *buffer);
DbgSetRegistersRequest *
       dbg_set_registers_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbg_set_registers_request__free_unpacked
                     (DbgSetRegistersRequest *message,
                      ProtobufCAllocator *allocator);
/* DbgGetThreadInfoRequest methods */
void   dbg_get_thread_info_request__init
                     (DbgGetThreadInfoRequest         *message);
size_t dbg_get_thread_info_request__get_packed_size
                     (const DbgGetThreadInfoRequest   *message);
size_t dbg_get_thread_info_request__pack
                     (const DbgGetThreadInfoRequest   *message,
                      uint8_t             *out);
size_t dbg_get_thread_info_request__pack_to_buffer
                     (const DbgGetThreadInfoRequest   *message,
                      ProtobufCBuffer     *buffer);
DbgGetThreadInfoRequest *
       dbg_get_thread_info_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbg_get_thread_info_request__free_unpacked
                     (DbgGetThreadInfoRequest *message,
                      ProtobufCAllocator *allocator);
/* DbgThreadSinglestepRequest methods */
void   dbg_thread_singlestep_request__init
                     (DbgThreadSinglestepRequest         *message);
size_t dbg_thread_singlestep_request__get_packed_size
                     (const DbgThreadSinglestepRequest   *message);
size_t dbg_thread_singlestep_request__pack
                     (const DbgThreadSinglestepRequest   *message,
                      uint8_t             *out);
size_t dbg_thread_singlestep_request__pack_to_buffer
                     (const DbgThreadSinglestepRequest   *message,
                      ProtobufCBuffer     *buffer);
DbgThreadSinglestepRequest *
       dbg_thread_singlestep_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbg_thread_singlestep_request__free_unpacked
                     (DbgThreadSinglestepRequest *message,
                      ProtobufCAllocator *allocator);
/* DbgGetKernelInfoResponse methods */
void   dbg_get_kernel_info_response__init
                     (DbgGetKernelInfoResponse         *message);
size_t dbg_get_kernel_info_response__get_packed_size
                     (const DbgGetKernelInfoResponse   *message);
size_t dbg_get_kernel_info_response__pack
                     (const DbgGetKernelInfoResponse   *message,
                      uint8_t             *out);
size_t dbg_get_kernel_info_response__pack_to_buffer
                     (const DbgGetKernelInfoResponse   *message,
                      ProtobufCBuffer     *buffer);
DbgGetKernelInfoResponse *
       dbg_get_kernel_info_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbg_get_kernel_info_response__free_unpacked
                     (DbgGetKernelInfoResponse *message,
                      ProtobufCAllocator *allocator);
/* DbgReadKernelMemoryRequest methods */
void   dbg_read_kernel_memory_request__init
                     (DbgReadKernelMemoryRequest         *message);
size_t dbg_read_kernel_memory_request__get_packed_size
                     (const DbgReadKernelMemoryRequest   *message);
size_t dbg_read_kernel_memory_request__pack
                     (const DbgReadKernelMemoryRequest   *message,
                      uint8_t             *out);
size_t dbg_read_kernel_memory_request__pack_to_buffer
                     (const DbgReadKernelMemoryRequest   *message,
                      ProtobufCBuffer     *buffer);
DbgReadKernelMemoryRequest *
       dbg_read_kernel_memory_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbg_read_kernel_memory_request__free_unpacked
                     (DbgReadKernelMemoryRequest *message,
                      ProtobufCAllocator *allocator);
/* DbgReadKernelMemoryResponse methods */
void   dbg_read_kernel_memory_response__init
                     (DbgReadKernelMemoryResponse         *message);
size_t dbg_read_kernel_memory_response__get_packed_size
                     (const DbgReadKernelMemoryResponse   *message);
size_t dbg_read_kernel_memory_response__pack
                     (const DbgReadKernelMemoryResponse   *message,
                      uint8_t             *out);
size_t dbg_read_kernel_memory_response__pack_to_buffer
                     (const DbgReadKernelMemoryResponse   *message,
                      ProtobufCBuffer     *buffer);
DbgReadKernelMemoryResponse *
       dbg_read_kernel_memory_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbg_read_kernel_memory_response__free_unpacked
                     (DbgReadKernelMemoryResponse *message,
                      ProtobufCAllocator *allocator);
/* DbgWriteKernelMemoryRequest methods */
void   dbg_write_kernel_memory_request__init
                     (DbgWriteKernelMemoryRequest         *message);
size_t dbg_write_kernel_memory_request__get_packed_size
                     (const DbgWriteKernelMemoryRequest   *message);
size_t dbg_write_kernel_memory_request__pack
                     (const DbgWriteKernelMemoryRequest   *message,
                      uint8_t             *out);
size_t dbg_write_kernel_memory_request__pack_to_buffer
                     (const DbgWriteKernelMemoryRequest   *message,
                      ProtobufCBuffer     *buffer);
DbgWriteKernelMemoryRequest *
       dbg_write_kernel_memory_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbg_write_kernel_memory_request__free_unpacked
                     (DbgWriteKernelMemoryRequest *message,
                      ProtobufCAllocator *allocator);
/* DbgCommandRequest methods */
void   dbg_command_request__init
                     (DbgCommandRequest         *message);
size_t dbg_command_request__get_packed_size
                     (const DbgCommandRequest   *message);
size_t dbg_command_request__pack
                     (const DbgCommandRequest   *message,
                      uint8_t             *out);
size_t dbg_command_request__pack_to_buffer
                     (const DbgCommandRequest   *message,
                      ProtobufCBuffer     *buffer);
DbgCommandRequest *
       dbg_command_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbg_command_request__free_unpacked
                     (DbgCommandRequest *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*DbgGetProcessListResponse_Closure)
                 (const DbgGetProcessListResponse *message,
                  void *closure_data);
typedef void (*DbgReadProcessMemoryRequest_Closure)
                 (const DbgReadProcessMemoryRequest *message,
                  void *closure_data);
typedef void (*DbgReadProcessMemoryResponse_Closure)
                 (const DbgReadProcessMemoryResponse *message,
                  void *closure_data);
typedef void (*DbgWriteProcessMemoryRequest_Closure)
                 (const DbgWriteProcessMemoryRequest *message,
                  void *closure_data);
typedef void (*DbgProtectProcessMemoryRequest_Closure)
                 (const DbgProtectProcessMemoryRequest *message,
                  void *closure_data);
typedef void (*DbgScanProcessMemoryRequest_Closure)
                 (const DbgScanProcessMemoryRequest *message,
                  void *closure_data);
typedef void (*DbgGetProcessInfoRequest_Closure)
                 (const DbgGetProcessInfoRequest *message,
                  void *closure_data);
typedef void (*DbgAllocateProcessMemoryRequest_Closure)
                 (const DbgAllocateProcessMemoryRequest *message,
                  void *closure_data);
typedef void (*DbgAllocateProcessMemoryResponse_Closure)
                 (const DbgAllocateProcessMemoryResponse *message,
                  void *closure_data);
typedef void (*DbgFreeProcessMemoryRequest_Closure)
                 (const DbgFreeProcessMemoryRequest *message,
                  void *closure_data);
typedef void (*DbgGetProcessMapsRequest_Closure)
                 (const DbgGetProcessMapsRequest *message,
                  void *closure_data);
typedef void (*DbgAttachRequest_Closure)
                 (const DbgAttachRequest *message,
                  void *closure_data);
typedef void (*DbgDetachRequest_Closure)
                 (const DbgDetachRequest *message,
                  void *closure_data);
typedef void (*DbgBreakpointRequest_Closure)
                 (const DbgBreakpointRequest *message,
                  void *closure_data);
typedef void (*DbgBreakpointResponse_Closure)
                 (const DbgBreakpointResponse *message,
                  void *closure_data);
typedef void (*DbgWatchpointRequest_Closure)
                 (const DbgWatchpointRequest *message,
                  void *closure_data);
typedef void (*DbgWatchpointResponse_Closure)
                 (const DbgWatchpointResponse *message,
                  void *closure_data);
typedef void (*DbgGetProcessThreadsRequest_Closure)
                 (const DbgGetProcessThreadsRequest *message,
                  void *closure_data);
typedef void (*DbgGetProcessThreadsResponse_Closure)
                 (const DbgGetProcessThreadsResponse *message,
                  void *closure_data);
typedef void (*DbgSignalProcessRequest_Closure)
                 (const DbgSignalProcessRequest *message,
                  void *closure_data);
typedef void (*DbgGetRegistersRequest_Closure)
                 (const DbgGetRegistersRequest *message,
                  void *closure_data);
typedef void (*DbgGetRegistersResponse_Closure)
                 (const DbgGetRegistersResponse *message,
                  void *closure_data);
typedef void (*DbgSetRegistersRequest_Closure)
                 (const DbgSetRegistersRequest *message,
                  void *closure_data);
typedef void (*DbgGetThreadInfoRequest_Closure)
                 (const DbgGetThreadInfoRequest *message,
                  void *closure_data);
typedef void (*DbgThreadSinglestepRequest_Closure)
                 (const DbgThreadSinglestepRequest *message,
                  void *closure_data);
typedef void (*DbgGetKernelInfoResponse_Closure)
                 (const DbgGetKernelInfoResponse *message,
                  void *closure_data);
typedef void (*DbgReadKernelMemoryRequest_Closure)
                 (const DbgReadKernelMemoryRequest *message,
                  void *closure_data);
typedef void (*DbgReadKernelMemoryResponse_Closure)
                 (const DbgReadKernelMemoryResponse *message,
                  void *closure_data);
typedef void (*DbgWriteKernelMemoryRequest_Closure)
                 (const DbgWriteKernelMemoryRequest *message,
                  void *closure_data);
typedef void (*DbgCommandRequest_Closure)
                 (const DbgCommandRequest *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    dbg_breakpoint_type__descriptor;
extern const ProtobufCMessageDescriptor dbg_get_process_list_response__descriptor;
extern const ProtobufCMessageDescriptor dbg_read_process_memory_request__descriptor;
extern const ProtobufCMessageDescriptor dbg_read_process_memory_response__descriptor;
extern const ProtobufCMessageDescriptor dbg_write_process_memory_request__descriptor;
extern const ProtobufCMessageDescriptor dbg_protect_process_memory_request__descriptor;
extern const ProtobufCMessageDescriptor dbg_scan_process_memory_request__descriptor;
extern const ProtobufCMessageDescriptor dbg_get_process_info_request__descriptor;
extern const ProtobufCMessageDescriptor dbg_allocate_process_memory_request__descriptor;
extern const ProtobufCMessageDescriptor dbg_allocate_process_memory_response__descriptor;
extern const ProtobufCMessageDescriptor dbg_free_process_memory_request__descriptor;
extern const ProtobufCMessageDescriptor dbg_get_process_maps_request__descriptor;
extern const ProtobufCMessageDescriptor dbg_attach_request__descriptor;
extern const ProtobufCMessageDescriptor dbg_detach_request__descriptor;
extern const ProtobufCMessageDescriptor dbg_breakpoint_request__descriptor;
extern const ProtobufCMessageDescriptor dbg_breakpoint_response__descriptor;
extern const ProtobufCMessageDescriptor dbg_watchpoint_request__descriptor;
extern const ProtobufCMessageDescriptor dbg_watchpoint_response__descriptor;
extern const ProtobufCMessageDescriptor dbg_get_process_threads_request__descriptor;
extern const ProtobufCMessageDescriptor dbg_get_process_threads_response__descriptor;
extern const ProtobufCMessageDescriptor dbg_signal_process_request__descriptor;
extern const ProtobufCMessageDescriptor dbg_get_registers_request__descriptor;
extern const ProtobufCMessageDescriptor dbg_get_registers_response__descriptor;
extern const ProtobufCMessageDescriptor dbg_set_registers_request__descriptor;
extern const ProtobufCMessageDescriptor dbg_get_thread_info_request__descriptor;
extern const ProtobufCMessageDescriptor dbg_thread_singlestep_request__descriptor;
extern const ProtobufCMessageDescriptor dbg_get_kernel_info_response__descriptor;
extern const ProtobufCMessageDescriptor dbg_read_kernel_memory_request__descriptor;
extern const ProtobufCMessageDescriptor dbg_read_kernel_memory_response__descriptor;
extern const ProtobufCMessageDescriptor dbg_write_kernel_memory_request__descriptor;
extern const ProtobufCMessageDescriptor dbg_command_request__descriptor;
extern const ProtobufCEnumDescriptor    dbg_command_request__dbg_commands__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_external_2fdebugger_2eproto__INCLUDED */
