/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: debugger.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "debugger.pb-c.h"
void   dbg_proc_list_request__init
                     (DbgProcListRequest         *message)
{
  static const DbgProcListRequest init_value = DBG_PROC_LIST_REQUEST__INIT;
  *message = init_value;
}
size_t dbg_proc_list_request__get_packed_size
                     (const DbgProcListRequest *message)
{
  assert(message->base.descriptor == &dbg_proc_list_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbg_proc_list_request__pack
                     (const DbgProcListRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbg_proc_list_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbg_proc_list_request__pack_to_buffer
                     (const DbgProcListRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbg_proc_list_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbgProcListRequest *
       dbg_proc_list_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbgProcListRequest *)
     protobuf_c_message_unpack (&dbg_proc_list_request__descriptor,
                                allocator, len, data);
}
void   dbg_proc_list_request__free_unpacked
                     (DbgProcListRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbg_proc_list_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
#define dbg_proc_list_request__field_descriptors NULL
#define dbg_proc_list_request__field_indices_by_name NULL
#define dbg_proc_list_request__number_ranges NULL
const ProtobufCMessageDescriptor dbg_proc_list_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DbgProcListRequest",
  "DbgProcListRequest",
  "DbgProcListRequest",
  "",
  sizeof(DbgProcListRequest),
  0,
  dbg_proc_list_request__field_descriptors,
  dbg_proc_list_request__field_indices_by_name,
  0,  dbg_proc_list_request__number_ranges,
  (ProtobufCMessageInit) dbg_proc_list_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
