/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: external/debugger_structs.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "debugger_structs.pb-c.h"
void   dbg_gp_registers__init
                     (DbgGpRegisters         *message)
{
  static const DbgGpRegisters init_value = DBG_GP_REGISTERS__INIT;
  *message = init_value;
}
size_t dbg_gp_registers__get_packed_size
                     (const DbgGpRegisters *message)
{
  assert(message->base.descriptor == &dbg_gp_registers__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbg_gp_registers__pack
                     (const DbgGpRegisters *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbg_gp_registers__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbg_gp_registers__pack_to_buffer
                     (const DbgGpRegisters *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbg_gp_registers__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbgGpRegisters *
       dbg_gp_registers__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbgGpRegisters *)
     protobuf_c_message_unpack (&dbg_gp_registers__descriptor,
                                allocator, len, data);
}
void   dbg_gp_registers__free_unpacked
                     (DbgGpRegisters *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbg_gp_registers__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbg_fp_registers__init
                     (DbgFpRegisters         *message)
{
  static const DbgFpRegisters init_value = DBG_FP_REGISTERS__INIT;
  *message = init_value;
}
size_t dbg_fp_registers__get_packed_size
                     (const DbgFpRegisters *message)
{
  assert(message->base.descriptor == &dbg_fp_registers__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbg_fp_registers__pack
                     (const DbgFpRegisters *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbg_fp_registers__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbg_fp_registers__pack_to_buffer
                     (const DbgFpRegisters *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbg_fp_registers__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbgFpRegisters *
       dbg_fp_registers__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbgFpRegisters *)
     protobuf_c_message_unpack (&dbg_fp_registers__descriptor,
                                allocator, len, data);
}
void   dbg_fp_registers__free_unpacked
                     (DbgFpRegisters *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbg_fp_registers__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbg_db_registers__init
                     (DbgDbRegisters         *message)
{
  static const DbgDbRegisters init_value = DBG_DB_REGISTERS__INIT;
  *message = init_value;
}
size_t dbg_db_registers__get_packed_size
                     (const DbgDbRegisters *message)
{
  assert(message->base.descriptor == &dbg_db_registers__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbg_db_registers__pack
                     (const DbgDbRegisters *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbg_db_registers__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbg_db_registers__pack_to_buffer
                     (const DbgDbRegisters *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbg_db_registers__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbgDbRegisters *
       dbg_db_registers__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbgDbRegisters *)
     protobuf_c_message_unpack (&dbg_db_registers__descriptor,
                                allocator, len, data);
}
void   dbg_db_registers__free_unpacked
                     (DbgDbRegisters *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbg_db_registers__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbg_thread_limited__init
                     (DbgThreadLimited         *message)
{
  static const DbgThreadLimited init_value = DBG_THREAD_LIMITED__INIT;
  *message = init_value;
}
size_t dbg_thread_limited__get_packed_size
                     (const DbgThreadLimited *message)
{
  assert(message->base.descriptor == &dbg_thread_limited__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbg_thread_limited__pack
                     (const DbgThreadLimited *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbg_thread_limited__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbg_thread_limited__pack_to_buffer
                     (const DbgThreadLimited *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbg_thread_limited__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbgThreadLimited *
       dbg_thread_limited__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbgThreadLimited *)
     protobuf_c_message_unpack (&dbg_thread_limited__descriptor,
                                allocator, len, data);
}
void   dbg_thread_limited__free_unpacked
                     (DbgThreadLimited *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbg_thread_limited__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbg_thread_full__init
                     (DbgThreadFull         *message)
{
  static const DbgThreadFull init_value = DBG_THREAD_FULL__INIT;
  *message = init_value;
}
size_t dbg_thread_full__get_packed_size
                     (const DbgThreadFull *message)
{
  assert(message->base.descriptor == &dbg_thread_full__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbg_thread_full__pack
                     (const DbgThreadFull *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbg_thread_full__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbg_thread_full__pack_to_buffer
                     (const DbgThreadFull *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbg_thread_full__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbgThreadFull *
       dbg_thread_full__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbgThreadFull *)
     protobuf_c_message_unpack (&dbg_thread_full__descriptor,
                                allocator, len, data);
}
void   dbg_thread_full__free_unpacked
                     (DbgThreadFull *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbg_thread_full__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbg_cred__init
                     (DbgCred         *message)
{
  static const DbgCred init_value = DBG_CRED__INIT;
  *message = init_value;
}
size_t dbg_cred__get_packed_size
                     (const DbgCred *message)
{
  assert(message->base.descriptor == &dbg_cred__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbg_cred__pack
                     (const DbgCred *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbg_cred__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbg_cred__pack_to_buffer
                     (const DbgCred *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbg_cred__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbgCred *
       dbg_cred__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbgCred *)
     protobuf_c_message_unpack (&dbg_cred__descriptor,
                                allocator, len, data);
}
void   dbg_cred__free_unpacked
                     (DbgCred *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbg_cred__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbg_file_desc__init
                     (DbgFileDesc         *message)
{
  static const DbgFileDesc init_value = DBG_FILE_DESC__INIT;
  *message = init_value;
}
size_t dbg_file_desc__get_packed_size
                     (const DbgFileDesc *message)
{
  assert(message->base.descriptor == &dbg_file_desc__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbg_file_desc__pack
                     (const DbgFileDesc *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbg_file_desc__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbg_file_desc__pack_to_buffer
                     (const DbgFileDesc *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbg_file_desc__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbgFileDesc *
       dbg_file_desc__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbgFileDesc *)
     protobuf_c_message_unpack (&dbg_file_desc__descriptor,
                                allocator, len, data);
}
void   dbg_file_desc__free_unpacked
                     (DbgFileDesc *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbg_file_desc__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbg_process_full__init
                     (DbgProcessFull         *message)
{
  static const DbgProcessFull init_value = DBG_PROCESS_FULL__INIT;
  *message = init_value;
}
size_t dbg_process_full__get_packed_size
                     (const DbgProcessFull *message)
{
  assert(message->base.descriptor == &dbg_process_full__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbg_process_full__pack
                     (const DbgProcessFull *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbg_process_full__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbg_process_full__pack_to_buffer
                     (const DbgProcessFull *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbg_process_full__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbgProcessFull *
       dbg_process_full__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbgProcessFull *)
     protobuf_c_message_unpack (&dbg_process_full__descriptor,
                                allocator, len, data);
}
void   dbg_process_full__free_unpacked
                     (DbgProcessFull *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbg_process_full__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbg_vm_entry__init
                     (DbgVmEntry         *message)
{
  static const DbgVmEntry init_value = DBG_VM_ENTRY__INIT;
  *message = init_value;
}
size_t dbg_vm_entry__get_packed_size
                     (const DbgVmEntry *message)
{
  assert(message->base.descriptor == &dbg_vm_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbg_vm_entry__pack
                     (const DbgVmEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbg_vm_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbg_vm_entry__pack_to_buffer
                     (const DbgVmEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbg_vm_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbgVmEntry *
       dbg_vm_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbgVmEntry *)
     protobuf_c_message_unpack (&dbg_vm_entry__descriptor,
                                allocator, len, data);
}
void   dbg_vm_entry__free_unpacked
                     (DbgVmEntry *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbg_vm_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbg_process_limited__init
                     (DbgProcessLimited         *message)
{
  static const DbgProcessLimited init_value = DBG_PROCESS_LIMITED__INIT;
  *message = init_value;
}
size_t dbg_process_limited__get_packed_size
                     (const DbgProcessLimited *message)
{
  assert(message->base.descriptor == &dbg_process_limited__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbg_process_limited__pack
                     (const DbgProcessLimited *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbg_process_limited__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbg_process_limited__pack_to_buffer
                     (const DbgProcessLimited *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbg_process_limited__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbgProcessLimited *
       dbg_process_limited__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbgProcessLimited *)
     protobuf_c_message_unpack (&dbg_process_limited__descriptor,
                                allocator, len, data);
}
void   dbg_process_limited__free_unpacked
                     (DbgProcessLimited *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbg_process_limited__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor dbg_gp_registers__field_descriptors[26] =
{
  {
    "r_r15",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DbgGpRegisters, r_r15),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r_r14",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DbgGpRegisters, r_r14),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r_r13",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DbgGpRegisters, r_r13),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r_r12",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DbgGpRegisters, r_r12),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r_r11",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DbgGpRegisters, r_r11),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r_r10",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DbgGpRegisters, r_r10),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r_r9",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DbgGpRegisters, r_r9),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r_r8",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DbgGpRegisters, r_r8),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r_rdi",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DbgGpRegisters, r_rdi),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r_rsi",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DbgGpRegisters, r_rsi),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r_rbp",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DbgGpRegisters, r_rbp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r_rbx",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DbgGpRegisters, r_rbx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r_rdx",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DbgGpRegisters, r_rdx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r_rcx",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DbgGpRegisters, r_rcx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r_rax",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DbgGpRegisters, r_rax),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r_trapno",
    16,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DbgGpRegisters, r_trapno),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r_fs",
    17,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DbgGpRegisters, r_fs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r_gs",
    18,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DbgGpRegisters, r_gs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r_err",
    19,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DbgGpRegisters, r_err),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r_es",
    20,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DbgGpRegisters, r_es),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r_ds",
    21,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DbgGpRegisters, r_ds),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r_rip",
    22,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DbgGpRegisters, r_rip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r_cs",
    23,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DbgGpRegisters, r_cs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r_rflags",
    24,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DbgGpRegisters, r_rflags),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r_rsp",
    25,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DbgGpRegisters, r_rsp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r_ss",
    26,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DbgGpRegisters, r_ss),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbg_gp_registers__field_indices_by_name[] = {
  22,   /* field[22] = r_cs */
  20,   /* field[20] = r_ds */
  18,   /* field[18] = r_err */
  19,   /* field[19] = r_es */
  16,   /* field[16] = r_fs */
  17,   /* field[17] = r_gs */
  5,   /* field[5] = r_r10 */
  4,   /* field[4] = r_r11 */
  3,   /* field[3] = r_r12 */
  2,   /* field[2] = r_r13 */
  1,   /* field[1] = r_r14 */
  0,   /* field[0] = r_r15 */
  7,   /* field[7] = r_r8 */
  6,   /* field[6] = r_r9 */
  14,   /* field[14] = r_rax */
  10,   /* field[10] = r_rbp */
  11,   /* field[11] = r_rbx */
  13,   /* field[13] = r_rcx */
  8,   /* field[8] = r_rdi */
  12,   /* field[12] = r_rdx */
  23,   /* field[23] = r_rflags */
  21,   /* field[21] = r_rip */
  9,   /* field[9] = r_rsi */
  24,   /* field[24] = r_rsp */
  25,   /* field[25] = r_ss */
  15,   /* field[15] = r_trapno */
};
static const ProtobufCIntRange dbg_gp_registers__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 26 }
};
const ProtobufCMessageDescriptor dbg_gp_registers__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DbgGpRegisters",
  "DbgGpRegisters",
  "DbgGpRegisters",
  "",
  sizeof(DbgGpRegisters),
  26,
  dbg_gp_registers__field_descriptors,
  dbg_gp_registers__field_indices_by_name,
  1,  dbg_gp_registers__number_ranges,
  (ProtobufCMessageInit) dbg_gp_registers__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dbg_fp_registers__field_descriptors[1] =
{
  {
    "data",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(DbgFpRegisters, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbg_fp_registers__field_indices_by_name[] = {
  0,   /* field[0] = data */
};
static const ProtobufCIntRange dbg_fp_registers__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dbg_fp_registers__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DbgFpRegisters",
  "DbgFpRegisters",
  "DbgFpRegisters",
  "",
  sizeof(DbgFpRegisters),
  1,
  dbg_fp_registers__field_descriptors,
  dbg_fp_registers__field_indices_by_name,
  1,  dbg_fp_registers__number_ranges,
  (ProtobufCMessageInit) dbg_fp_registers__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dbg_db_registers__field_descriptors[1] =
{
  {
    "debugRegs",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DbgDbRegisters, n_debugregs),
    offsetof(DbgDbRegisters, debugregs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbg_db_registers__field_indices_by_name[] = {
  0,   /* field[0] = debugRegs */
};
static const ProtobufCIntRange dbg_db_registers__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dbg_db_registers__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DbgDbRegisters",
  "DbgDbRegisters",
  "DbgDbRegisters",
  "",
  sizeof(DbgDbRegisters),
  1,
  dbg_db_registers__field_descriptors,
  dbg_db_registers__field_indices_by_name,
  1,  dbg_db_registers__number_ranges,
  (ProtobufCMessageInit) dbg_db_registers__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dbg_thread_limited__field_descriptors[7] =
{
  {
    "proc",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DbgThreadLimited, proc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "threadId",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DbgThreadLimited, threadid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DbgThreadLimited, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "retval",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(DbgThreadLimited, retval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kernelStack",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DbgThreadLimited, kernelstack),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kernelStackPages",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DbgThreadLimited, kernelstackpages),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "err_no",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DbgThreadLimited, err_no),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbg_thread_limited__field_indices_by_name[] = {
  6,   /* field[6] = err_no */
  4,   /* field[4] = kernelStack */
  5,   /* field[5] = kernelStackPages */
  2,   /* field[2] = name */
  0,   /* field[0] = proc */
  3,   /* field[3] = retval */
  1,   /* field[1] = threadId */
};
static const ProtobufCIntRange dbg_thread_limited__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor dbg_thread_limited__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DbgThreadLimited",
  "DbgThreadLimited",
  "DbgThreadLimited",
  "",
  sizeof(DbgThreadLimited),
  7,
  dbg_thread_limited__field_descriptors,
  dbg_thread_limited__field_indices_by_name,
  1,  dbg_thread_limited__number_ranges,
  (ProtobufCMessageInit) dbg_thread_limited__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dbg_thread_full__field_descriptors[10] =
{
  {
    "proc",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DbgThreadFull, proc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "threadId",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DbgThreadFull, threadid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DbgThreadFull, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "retval",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(DbgThreadFull, retval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kernelStack",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DbgThreadFull, kernelstack),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kernelStackPages",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DbgThreadFull, kernelstackpages),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "err_no",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DbgThreadFull, err_no),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gpRegisters",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DbgThreadFull, gpregisters),
    &dbg_gp_registers__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fpRegisters",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DbgThreadFull, fpregisters),
    &dbg_fp_registers__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dbRegisters",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DbgThreadFull, dbregisters),
    &dbg_db_registers__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbg_thread_full__field_indices_by_name[] = {
  9,   /* field[9] = dbRegisters */
  6,   /* field[6] = err_no */
  8,   /* field[8] = fpRegisters */
  7,   /* field[7] = gpRegisters */
  4,   /* field[4] = kernelStack */
  5,   /* field[5] = kernelStackPages */
  2,   /* field[2] = name */
  0,   /* field[0] = proc */
  3,   /* field[3] = retval */
  1,   /* field[1] = threadId */
};
static const ProtobufCIntRange dbg_thread_full__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor dbg_thread_full__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DbgThreadFull",
  "DbgThreadFull",
  "DbgThreadFull",
  "",
  sizeof(DbgThreadFull),
  10,
  dbg_thread_full__field_descriptors,
  dbg_thread_full__field_indices_by_name,
  1,  dbg_thread_full__number_ranges,
  (ProtobufCMessageInit) dbg_thread_full__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dbg_cred__field_descriptors[10] =
{
  {
    "effectiveUserId",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DbgCred, effectiveuserid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "realUserId",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DbgCred, realuserid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "savedUserId",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DbgCred, saveduserid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "numGroups",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DbgCred, numgroups),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "realGroupId",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DbgCred, realgroupid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "savedGroupId",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DbgCred, savedgroupid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "prison",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DbgCred, prison),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sceAuthId",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DbgCred, sceauthid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sceCaps",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(DbgCred, n_scecaps),
    offsetof(DbgCred, scecaps),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sceAttr",
    10,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(DbgCred, n_sceattr),
    offsetof(DbgCred, sceattr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbg_cred__field_indices_by_name[] = {
  0,   /* field[0] = effectiveUserId */
  3,   /* field[3] = numGroups */
  6,   /* field[6] = prison */
  4,   /* field[4] = realGroupId */
  1,   /* field[1] = realUserId */
  5,   /* field[5] = savedGroupId */
  2,   /* field[2] = savedUserId */
  9,   /* field[9] = sceAttr */
  7,   /* field[7] = sceAuthId */
  8,   /* field[8] = sceCaps */
};
static const ProtobufCIntRange dbg_cred__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor dbg_cred__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DbgCred",
  "DbgCred",
  "DbgCred",
  "",
  sizeof(DbgCred),
  10,
  dbg_cred__field_descriptors,
  dbg_cred__field_indices_by_name,
  1,  dbg_cred__number_ranges,
  (ProtobufCMessageInit) dbg_cred__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define dbg_file_desc__field_descriptors NULL
#define dbg_file_desc__field_indices_by_name NULL
#define dbg_file_desc__number_ranges NULL
const ProtobufCMessageDescriptor dbg_file_desc__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DbgFileDesc",
  "DbgFileDesc",
  "DbgFileDesc",
  "",
  sizeof(DbgFileDesc),
  0,
  dbg_file_desc__field_descriptors,
  dbg_file_desc__field_indices_by_name,
  0,  dbg_file_desc__number_ranges,
  (ProtobufCMessageInit) dbg_file_desc__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dbg_process_full__field_descriptors[21] =
{
  {
    "threads",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DbgProcessFull, n_threads),
    offsetof(DbgProcessFull, threads),
    &dbg_thread_limited__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cred",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DbgProcessFull, cred),
    &dbg_cred__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "processId",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DbgProcessFull, processid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "parentProc",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DbgProcessFull, parentproc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "oppid",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DbgProcessFull, oppid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dbgChild",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DbgProcessFull, dbgchild),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vmspace",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DbgProcessFull, vmspace),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "exitThreads",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DbgProcessFull, exitthreads),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sigParent",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DbgProcessFull, sigparent),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sig",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DbgProcessFull, sig),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "code",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DbgProcessFull, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stops",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DbgProcessFull, stops),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stype",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DbgProcessFull, stype),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "singleThread",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DbgProcessFull, singlethread),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "suspendCount",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DbgProcessFull, suspendcount),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dynlib",
    16,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DbgProcessFull, dynlib),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    17,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DbgProcessFull, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "elfPath",
    18,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DbgProcessFull, elfpath),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "randomizedPath",
    19,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DbgProcessFull, randomizedpath),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "numThreads",
    20,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DbgProcessFull, numthreads),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mapEntries",
    21,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DbgProcessFull, n_mapentries),
    offsetof(DbgProcessFull, mapentries),
    &dbg_vm_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbg_process_full__field_indices_by_name[] = {
  10,   /* field[10] = code */
  1,   /* field[1] = cred */
  5,   /* field[5] = dbgChild */
  15,   /* field[15] = dynlib */
  17,   /* field[17] = elfPath */
  7,   /* field[7] = exitThreads */
  20,   /* field[20] = mapEntries */
  16,   /* field[16] = name */
  19,   /* field[19] = numThreads */
  4,   /* field[4] = oppid */
  3,   /* field[3] = parentProc */
  2,   /* field[2] = processId */
  18,   /* field[18] = randomizedPath */
  9,   /* field[9] = sig */
  8,   /* field[8] = sigParent */
  13,   /* field[13] = singleThread */
  11,   /* field[11] = stops */
  12,   /* field[12] = stype */
  14,   /* field[14] = suspendCount */
  0,   /* field[0] = threads */
  6,   /* field[6] = vmspace */
};
static const ProtobufCIntRange dbg_process_full__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 21 }
};
const ProtobufCMessageDescriptor dbg_process_full__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DbgProcessFull",
  "DbgProcessFull",
  "DbgProcessFull",
  "",
  sizeof(DbgProcessFull),
  21,
  dbg_process_full__field_descriptors,
  dbg_process_full__field_indices_by_name,
  1,  dbg_process_full__number_ranges,
  (ProtobufCMessageInit) dbg_process_full__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dbg_vm_entry__field_descriptors[5] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DbgVmEntry, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DbgVmEntry, start),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "end",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DbgVmEntry, end),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "offset",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DbgVmEntry, offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "protection",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DbgVmEntry, protection),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbg_vm_entry__field_indices_by_name[] = {
  2,   /* field[2] = end */
  0,   /* field[0] = name */
  3,   /* field[3] = offset */
  4,   /* field[4] = protection */
  1,   /* field[1] = start */
};
static const ProtobufCIntRange dbg_vm_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor dbg_vm_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DbgVmEntry",
  "DbgVmEntry",
  "DbgVmEntry",
  "",
  sizeof(DbgVmEntry),
  5,
  dbg_vm_entry__field_descriptors,
  dbg_vm_entry__field_indices_by_name,
  1,  dbg_vm_entry__number_ranges,
  (ProtobufCMessageInit) dbg_vm_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dbg_process_limited__field_descriptors[3] =
{
  {
    "processId",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DbgProcessLimited, processid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DbgProcessLimited, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "entries",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DbgProcessLimited, n_entries),
    offsetof(DbgProcessLimited, entries),
    &dbg_vm_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbg_process_limited__field_indices_by_name[] = {
  2,   /* field[2] = entries */
  1,   /* field[1] = name */
  0,   /* field[0] = processId */
};
static const ProtobufCIntRange dbg_process_limited__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor dbg_process_limited__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DbgProcessLimited",
  "DbgProcessLimited",
  "DbgProcessLimited",
  "",
  sizeof(DbgProcessLimited),
  3,
  dbg_process_limited__field_descriptors,
  dbg_process_limited__field_indices_by_name,
  1,  dbg_process_limited__number_ranges,
  (ProtobufCMessageInit) dbg_process_limited__init,
  NULL,NULL,NULL    /* reserved[123] */
};
