/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: external/debugger.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "debugger.pb-c.h"
void   dbg_get_process_list_response__init
                     (DbgGetProcessListResponse         *message)
{
  static const DbgGetProcessListResponse init_value = DBG_GET_PROCESS_LIST_RESPONSE__INIT;
  *message = init_value;
}
size_t dbg_get_process_list_response__get_packed_size
                     (const DbgGetProcessListResponse *message)
{
  assert(message->base.descriptor == &dbg_get_process_list_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbg_get_process_list_response__pack
                     (const DbgGetProcessListResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbg_get_process_list_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbg_get_process_list_response__pack_to_buffer
                     (const DbgGetProcessListResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbg_get_process_list_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbgGetProcessListResponse *
       dbg_get_process_list_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbgGetProcessListResponse *)
     protobuf_c_message_unpack (&dbg_get_process_list_response__descriptor,
                                allocator, len, data);
}
void   dbg_get_process_list_response__free_unpacked
                     (DbgGetProcessListResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbg_get_process_list_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbg_read_process_memory_request__init
                     (DbgReadProcessMemoryRequest         *message)
{
  static const DbgReadProcessMemoryRequest init_value = DBG_READ_PROCESS_MEMORY_REQUEST__INIT;
  *message = init_value;
}
size_t dbg_read_process_memory_request__get_packed_size
                     (const DbgReadProcessMemoryRequest *message)
{
  assert(message->base.descriptor == &dbg_read_process_memory_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbg_read_process_memory_request__pack
                     (const DbgReadProcessMemoryRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbg_read_process_memory_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbg_read_process_memory_request__pack_to_buffer
                     (const DbgReadProcessMemoryRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbg_read_process_memory_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbgReadProcessMemoryRequest *
       dbg_read_process_memory_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbgReadProcessMemoryRequest *)
     protobuf_c_message_unpack (&dbg_read_process_memory_request__descriptor,
                                allocator, len, data);
}
void   dbg_read_process_memory_request__free_unpacked
                     (DbgReadProcessMemoryRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbg_read_process_memory_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbg_read_process_memory_response__init
                     (DbgReadProcessMemoryResponse         *message)
{
  static const DbgReadProcessMemoryResponse init_value = DBG_READ_PROCESS_MEMORY_RESPONSE__INIT;
  *message = init_value;
}
size_t dbg_read_process_memory_response__get_packed_size
                     (const DbgReadProcessMemoryResponse *message)
{
  assert(message->base.descriptor == &dbg_read_process_memory_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbg_read_process_memory_response__pack
                     (const DbgReadProcessMemoryResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbg_read_process_memory_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbg_read_process_memory_response__pack_to_buffer
                     (const DbgReadProcessMemoryResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbg_read_process_memory_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbgReadProcessMemoryResponse *
       dbg_read_process_memory_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbgReadProcessMemoryResponse *)
     protobuf_c_message_unpack (&dbg_read_process_memory_response__descriptor,
                                allocator, len, data);
}
void   dbg_read_process_memory_response__free_unpacked
                     (DbgReadProcessMemoryResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbg_read_process_memory_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbg_write_process_memory_request__init
                     (DbgWriteProcessMemoryRequest         *message)
{
  static const DbgWriteProcessMemoryRequest init_value = DBG_WRITE_PROCESS_MEMORY_REQUEST__INIT;
  *message = init_value;
}
size_t dbg_write_process_memory_request__get_packed_size
                     (const DbgWriteProcessMemoryRequest *message)
{
  assert(message->base.descriptor == &dbg_write_process_memory_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbg_write_process_memory_request__pack
                     (const DbgWriteProcessMemoryRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbg_write_process_memory_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbg_write_process_memory_request__pack_to_buffer
                     (const DbgWriteProcessMemoryRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbg_write_process_memory_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbgWriteProcessMemoryRequest *
       dbg_write_process_memory_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbgWriteProcessMemoryRequest *)
     protobuf_c_message_unpack (&dbg_write_process_memory_request__descriptor,
                                allocator, len, data);
}
void   dbg_write_process_memory_request__free_unpacked
                     (DbgWriteProcessMemoryRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbg_write_process_memory_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbg_protect_process_memory_request__init
                     (DbgProtectProcessMemoryRequest         *message)
{
  static const DbgProtectProcessMemoryRequest init_value = DBG_PROTECT_PROCESS_MEMORY_REQUEST__INIT;
  *message = init_value;
}
size_t dbg_protect_process_memory_request__get_packed_size
                     (const DbgProtectProcessMemoryRequest *message)
{
  assert(message->base.descriptor == &dbg_protect_process_memory_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbg_protect_process_memory_request__pack
                     (const DbgProtectProcessMemoryRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbg_protect_process_memory_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbg_protect_process_memory_request__pack_to_buffer
                     (const DbgProtectProcessMemoryRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbg_protect_process_memory_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbgProtectProcessMemoryRequest *
       dbg_protect_process_memory_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbgProtectProcessMemoryRequest *)
     protobuf_c_message_unpack (&dbg_protect_process_memory_request__descriptor,
                                allocator, len, data);
}
void   dbg_protect_process_memory_request__free_unpacked
                     (DbgProtectProcessMemoryRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbg_protect_process_memory_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbg_scan_process_memory_request__init
                     (DbgScanProcessMemoryRequest         *message)
{
  static const DbgScanProcessMemoryRequest init_value = DBG_SCAN_PROCESS_MEMORY_REQUEST__INIT;
  *message = init_value;
}
size_t dbg_scan_process_memory_request__get_packed_size
                     (const DbgScanProcessMemoryRequest *message)
{
  assert(message->base.descriptor == &dbg_scan_process_memory_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbg_scan_process_memory_request__pack
                     (const DbgScanProcessMemoryRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbg_scan_process_memory_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbg_scan_process_memory_request__pack_to_buffer
                     (const DbgScanProcessMemoryRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbg_scan_process_memory_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbgScanProcessMemoryRequest *
       dbg_scan_process_memory_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbgScanProcessMemoryRequest *)
     protobuf_c_message_unpack (&dbg_scan_process_memory_request__descriptor,
                                allocator, len, data);
}
void   dbg_scan_process_memory_request__free_unpacked
                     (DbgScanProcessMemoryRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbg_scan_process_memory_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbg_get_process_info_request__init
                     (DbgGetProcessInfoRequest         *message)
{
  static const DbgGetProcessInfoRequest init_value = DBG_GET_PROCESS_INFO_REQUEST__INIT;
  *message = init_value;
}
size_t dbg_get_process_info_request__get_packed_size
                     (const DbgGetProcessInfoRequest *message)
{
  assert(message->base.descriptor == &dbg_get_process_info_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbg_get_process_info_request__pack
                     (const DbgGetProcessInfoRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbg_get_process_info_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbg_get_process_info_request__pack_to_buffer
                     (const DbgGetProcessInfoRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbg_get_process_info_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbgGetProcessInfoRequest *
       dbg_get_process_info_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbgGetProcessInfoRequest *)
     protobuf_c_message_unpack (&dbg_get_process_info_request__descriptor,
                                allocator, len, data);
}
void   dbg_get_process_info_request__free_unpacked
                     (DbgGetProcessInfoRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbg_get_process_info_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbg_allocate_process_memory_request__init
                     (DbgAllocateProcessMemoryRequest         *message)
{
  static const DbgAllocateProcessMemoryRequest init_value = DBG_ALLOCATE_PROCESS_MEMORY_REQUEST__INIT;
  *message = init_value;
}
size_t dbg_allocate_process_memory_request__get_packed_size
                     (const DbgAllocateProcessMemoryRequest *message)
{
  assert(message->base.descriptor == &dbg_allocate_process_memory_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbg_allocate_process_memory_request__pack
                     (const DbgAllocateProcessMemoryRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbg_allocate_process_memory_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbg_allocate_process_memory_request__pack_to_buffer
                     (const DbgAllocateProcessMemoryRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbg_allocate_process_memory_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbgAllocateProcessMemoryRequest *
       dbg_allocate_process_memory_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbgAllocateProcessMemoryRequest *)
     protobuf_c_message_unpack (&dbg_allocate_process_memory_request__descriptor,
                                allocator, len, data);
}
void   dbg_allocate_process_memory_request__free_unpacked
                     (DbgAllocateProcessMemoryRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbg_allocate_process_memory_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbg_allocate_process_memory_response__init
                     (DbgAllocateProcessMemoryResponse         *message)
{
  static const DbgAllocateProcessMemoryResponse init_value = DBG_ALLOCATE_PROCESS_MEMORY_RESPONSE__INIT;
  *message = init_value;
}
size_t dbg_allocate_process_memory_response__get_packed_size
                     (const DbgAllocateProcessMemoryResponse *message)
{
  assert(message->base.descriptor == &dbg_allocate_process_memory_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbg_allocate_process_memory_response__pack
                     (const DbgAllocateProcessMemoryResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbg_allocate_process_memory_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbg_allocate_process_memory_response__pack_to_buffer
                     (const DbgAllocateProcessMemoryResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbg_allocate_process_memory_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbgAllocateProcessMemoryResponse *
       dbg_allocate_process_memory_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbgAllocateProcessMemoryResponse *)
     protobuf_c_message_unpack (&dbg_allocate_process_memory_response__descriptor,
                                allocator, len, data);
}
void   dbg_allocate_process_memory_response__free_unpacked
                     (DbgAllocateProcessMemoryResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbg_allocate_process_memory_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbg_free_process_memory_request__init
                     (DbgFreeProcessMemoryRequest         *message)
{
  static const DbgFreeProcessMemoryRequest init_value = DBG_FREE_PROCESS_MEMORY_REQUEST__INIT;
  *message = init_value;
}
size_t dbg_free_process_memory_request__get_packed_size
                     (const DbgFreeProcessMemoryRequest *message)
{
  assert(message->base.descriptor == &dbg_free_process_memory_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbg_free_process_memory_request__pack
                     (const DbgFreeProcessMemoryRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbg_free_process_memory_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbg_free_process_memory_request__pack_to_buffer
                     (const DbgFreeProcessMemoryRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbg_free_process_memory_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbgFreeProcessMemoryRequest *
       dbg_free_process_memory_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbgFreeProcessMemoryRequest *)
     protobuf_c_message_unpack (&dbg_free_process_memory_request__descriptor,
                                allocator, len, data);
}
void   dbg_free_process_memory_request__free_unpacked
                     (DbgFreeProcessMemoryRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbg_free_process_memory_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbg_get_process_maps_request__init
                     (DbgGetProcessMapsRequest         *message)
{
  static const DbgGetProcessMapsRequest init_value = DBG_GET_PROCESS_MAPS_REQUEST__INIT;
  *message = init_value;
}
size_t dbg_get_process_maps_request__get_packed_size
                     (const DbgGetProcessMapsRequest *message)
{
  assert(message->base.descriptor == &dbg_get_process_maps_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbg_get_process_maps_request__pack
                     (const DbgGetProcessMapsRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbg_get_process_maps_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbg_get_process_maps_request__pack_to_buffer
                     (const DbgGetProcessMapsRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbg_get_process_maps_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbgGetProcessMapsRequest *
       dbg_get_process_maps_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbgGetProcessMapsRequest *)
     protobuf_c_message_unpack (&dbg_get_process_maps_request__descriptor,
                                allocator, len, data);
}
void   dbg_get_process_maps_request__free_unpacked
                     (DbgGetProcessMapsRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbg_get_process_maps_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbg_attach_request__init
                     (DbgAttachRequest         *message)
{
  static const DbgAttachRequest init_value = DBG_ATTACH_REQUEST__INIT;
  *message = init_value;
}
size_t dbg_attach_request__get_packed_size
                     (const DbgAttachRequest *message)
{
  assert(message->base.descriptor == &dbg_attach_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbg_attach_request__pack
                     (const DbgAttachRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbg_attach_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbg_attach_request__pack_to_buffer
                     (const DbgAttachRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbg_attach_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbgAttachRequest *
       dbg_attach_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbgAttachRequest *)
     protobuf_c_message_unpack (&dbg_attach_request__descriptor,
                                allocator, len, data);
}
void   dbg_attach_request__free_unpacked
                     (DbgAttachRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbg_attach_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbg_detach_request__init
                     (DbgDetachRequest         *message)
{
  static const DbgDetachRequest init_value = DBG_DETACH_REQUEST__INIT;
  *message = init_value;
}
size_t dbg_detach_request__get_packed_size
                     (const DbgDetachRequest *message)
{
  assert(message->base.descriptor == &dbg_detach_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbg_detach_request__pack
                     (const DbgDetachRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbg_detach_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbg_detach_request__pack_to_buffer
                     (const DbgDetachRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbg_detach_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbgDetachRequest *
       dbg_detach_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbgDetachRequest *)
     protobuf_c_message_unpack (&dbg_detach_request__descriptor,
                                allocator, len, data);
}
void   dbg_detach_request__free_unpacked
                     (DbgDetachRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbg_detach_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbg_breakpoint_request__init
                     (DbgBreakpointRequest         *message)
{
  static const DbgBreakpointRequest init_value = DBG_BREAKPOINT_REQUEST__INIT;
  *message = init_value;
}
size_t dbg_breakpoint_request__get_packed_size
                     (const DbgBreakpointRequest *message)
{
  assert(message->base.descriptor == &dbg_breakpoint_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbg_breakpoint_request__pack
                     (const DbgBreakpointRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbg_breakpoint_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbg_breakpoint_request__pack_to_buffer
                     (const DbgBreakpointRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbg_breakpoint_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbgBreakpointRequest *
       dbg_breakpoint_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbgBreakpointRequest *)
     protobuf_c_message_unpack (&dbg_breakpoint_request__descriptor,
                                allocator, len, data);
}
void   dbg_breakpoint_request__free_unpacked
                     (DbgBreakpointRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbg_breakpoint_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbg_breakpoint_response__init
                     (DbgBreakpointResponse         *message)
{
  static const DbgBreakpointResponse init_value = DBG_BREAKPOINT_RESPONSE__INIT;
  *message = init_value;
}
size_t dbg_breakpoint_response__get_packed_size
                     (const DbgBreakpointResponse *message)
{
  assert(message->base.descriptor == &dbg_breakpoint_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbg_breakpoint_response__pack
                     (const DbgBreakpointResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbg_breakpoint_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbg_breakpoint_response__pack_to_buffer
                     (const DbgBreakpointResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbg_breakpoint_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbgBreakpointResponse *
       dbg_breakpoint_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbgBreakpointResponse *)
     protobuf_c_message_unpack (&dbg_breakpoint_response__descriptor,
                                allocator, len, data);
}
void   dbg_breakpoint_response__free_unpacked
                     (DbgBreakpointResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbg_breakpoint_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbg_watchpoint_request__init
                     (DbgWatchpointRequest         *message)
{
  static const DbgWatchpointRequest init_value = DBG_WATCHPOINT_REQUEST__INIT;
  *message = init_value;
}
size_t dbg_watchpoint_request__get_packed_size
                     (const DbgWatchpointRequest *message)
{
  assert(message->base.descriptor == &dbg_watchpoint_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbg_watchpoint_request__pack
                     (const DbgWatchpointRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbg_watchpoint_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbg_watchpoint_request__pack_to_buffer
                     (const DbgWatchpointRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbg_watchpoint_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbgWatchpointRequest *
       dbg_watchpoint_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbgWatchpointRequest *)
     protobuf_c_message_unpack (&dbg_watchpoint_request__descriptor,
                                allocator, len, data);
}
void   dbg_watchpoint_request__free_unpacked
                     (DbgWatchpointRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbg_watchpoint_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbg_watchpoint_response__init
                     (DbgWatchpointResponse         *message)
{
  static const DbgWatchpointResponse init_value = DBG_WATCHPOINT_RESPONSE__INIT;
  *message = init_value;
}
size_t dbg_watchpoint_response__get_packed_size
                     (const DbgWatchpointResponse *message)
{
  assert(message->base.descriptor == &dbg_watchpoint_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbg_watchpoint_response__pack
                     (const DbgWatchpointResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbg_watchpoint_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbg_watchpoint_response__pack_to_buffer
                     (const DbgWatchpointResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbg_watchpoint_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbgWatchpointResponse *
       dbg_watchpoint_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbgWatchpointResponse *)
     protobuf_c_message_unpack (&dbg_watchpoint_response__descriptor,
                                allocator, len, data);
}
void   dbg_watchpoint_response__free_unpacked
                     (DbgWatchpointResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbg_watchpoint_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbg_get_process_threads_request__init
                     (DbgGetProcessThreadsRequest         *message)
{
  static const DbgGetProcessThreadsRequest init_value = DBG_GET_PROCESS_THREADS_REQUEST__INIT;
  *message = init_value;
}
size_t dbg_get_process_threads_request__get_packed_size
                     (const DbgGetProcessThreadsRequest *message)
{
  assert(message->base.descriptor == &dbg_get_process_threads_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbg_get_process_threads_request__pack
                     (const DbgGetProcessThreadsRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbg_get_process_threads_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbg_get_process_threads_request__pack_to_buffer
                     (const DbgGetProcessThreadsRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbg_get_process_threads_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbgGetProcessThreadsRequest *
       dbg_get_process_threads_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbgGetProcessThreadsRequest *)
     protobuf_c_message_unpack (&dbg_get_process_threads_request__descriptor,
                                allocator, len, data);
}
void   dbg_get_process_threads_request__free_unpacked
                     (DbgGetProcessThreadsRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbg_get_process_threads_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbg_get_process_threads_response__init
                     (DbgGetProcessThreadsResponse         *message)
{
  static const DbgGetProcessThreadsResponse init_value = DBG_GET_PROCESS_THREADS_RESPONSE__INIT;
  *message = init_value;
}
size_t dbg_get_process_threads_response__get_packed_size
                     (const DbgGetProcessThreadsResponse *message)
{
  assert(message->base.descriptor == &dbg_get_process_threads_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbg_get_process_threads_response__pack
                     (const DbgGetProcessThreadsResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbg_get_process_threads_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbg_get_process_threads_response__pack_to_buffer
                     (const DbgGetProcessThreadsResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbg_get_process_threads_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbgGetProcessThreadsResponse *
       dbg_get_process_threads_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbgGetProcessThreadsResponse *)
     protobuf_c_message_unpack (&dbg_get_process_threads_response__descriptor,
                                allocator, len, data);
}
void   dbg_get_process_threads_response__free_unpacked
                     (DbgGetProcessThreadsResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbg_get_process_threads_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbg_signal_process_request__init
                     (DbgSignalProcessRequest         *message)
{
  static const DbgSignalProcessRequest init_value = DBG_SIGNAL_PROCESS_REQUEST__INIT;
  *message = init_value;
}
size_t dbg_signal_process_request__get_packed_size
                     (const DbgSignalProcessRequest *message)
{
  assert(message->base.descriptor == &dbg_signal_process_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbg_signal_process_request__pack
                     (const DbgSignalProcessRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbg_signal_process_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbg_signal_process_request__pack_to_buffer
                     (const DbgSignalProcessRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbg_signal_process_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbgSignalProcessRequest *
       dbg_signal_process_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbgSignalProcessRequest *)
     protobuf_c_message_unpack (&dbg_signal_process_request__descriptor,
                                allocator, len, data);
}
void   dbg_signal_process_request__free_unpacked
                     (DbgSignalProcessRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbg_signal_process_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbg_get_registers_request__init
                     (DbgGetRegistersRequest         *message)
{
  static const DbgGetRegistersRequest init_value = DBG_GET_REGISTERS_REQUEST__INIT;
  *message = init_value;
}
size_t dbg_get_registers_request__get_packed_size
                     (const DbgGetRegistersRequest *message)
{
  assert(message->base.descriptor == &dbg_get_registers_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbg_get_registers_request__pack
                     (const DbgGetRegistersRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbg_get_registers_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbg_get_registers_request__pack_to_buffer
                     (const DbgGetRegistersRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbg_get_registers_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbgGetRegistersRequest *
       dbg_get_registers_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbgGetRegistersRequest *)
     protobuf_c_message_unpack (&dbg_get_registers_request__descriptor,
                                allocator, len, data);
}
void   dbg_get_registers_request__free_unpacked
                     (DbgGetRegistersRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbg_get_registers_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbg_get_registers_response__init
                     (DbgGetRegistersResponse         *message)
{
  static const DbgGetRegistersResponse init_value = DBG_GET_REGISTERS_RESPONSE__INIT;
  *message = init_value;
}
size_t dbg_get_registers_response__get_packed_size
                     (const DbgGetRegistersResponse *message)
{
  assert(message->base.descriptor == &dbg_get_registers_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbg_get_registers_response__pack
                     (const DbgGetRegistersResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbg_get_registers_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbg_get_registers_response__pack_to_buffer
                     (const DbgGetRegistersResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbg_get_registers_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbgGetRegistersResponse *
       dbg_get_registers_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbgGetRegistersResponse *)
     protobuf_c_message_unpack (&dbg_get_registers_response__descriptor,
                                allocator, len, data);
}
void   dbg_get_registers_response__free_unpacked
                     (DbgGetRegistersResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbg_get_registers_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbg_set_registers_request__init
                     (DbgSetRegistersRequest         *message)
{
  static const DbgSetRegistersRequest init_value = DBG_SET_REGISTERS_REQUEST__INIT;
  *message = init_value;
}
size_t dbg_set_registers_request__get_packed_size
                     (const DbgSetRegistersRequest *message)
{
  assert(message->base.descriptor == &dbg_set_registers_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbg_set_registers_request__pack
                     (const DbgSetRegistersRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbg_set_registers_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbg_set_registers_request__pack_to_buffer
                     (const DbgSetRegistersRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbg_set_registers_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbgSetRegistersRequest *
       dbg_set_registers_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbgSetRegistersRequest *)
     protobuf_c_message_unpack (&dbg_set_registers_request__descriptor,
                                allocator, len, data);
}
void   dbg_set_registers_request__free_unpacked
                     (DbgSetRegistersRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbg_set_registers_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbg_get_thread_info_request__init
                     (DbgGetThreadInfoRequest         *message)
{
  static const DbgGetThreadInfoRequest init_value = DBG_GET_THREAD_INFO_REQUEST__INIT;
  *message = init_value;
}
size_t dbg_get_thread_info_request__get_packed_size
                     (const DbgGetThreadInfoRequest *message)
{
  assert(message->base.descriptor == &dbg_get_thread_info_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbg_get_thread_info_request__pack
                     (const DbgGetThreadInfoRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbg_get_thread_info_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbg_get_thread_info_request__pack_to_buffer
                     (const DbgGetThreadInfoRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbg_get_thread_info_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbgGetThreadInfoRequest *
       dbg_get_thread_info_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbgGetThreadInfoRequest *)
     protobuf_c_message_unpack (&dbg_get_thread_info_request__descriptor,
                                allocator, len, data);
}
void   dbg_get_thread_info_request__free_unpacked
                     (DbgGetThreadInfoRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbg_get_thread_info_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbg_get_kernel_info_response__init
                     (DbgGetKernelInfoResponse         *message)
{
  static const DbgGetKernelInfoResponse init_value = DBG_GET_KERNEL_INFO_RESPONSE__INIT;
  *message = init_value;
}
size_t dbg_get_kernel_info_response__get_packed_size
                     (const DbgGetKernelInfoResponse *message)
{
  assert(message->base.descriptor == &dbg_get_kernel_info_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbg_get_kernel_info_response__pack
                     (const DbgGetKernelInfoResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbg_get_kernel_info_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbg_get_kernel_info_response__pack_to_buffer
                     (const DbgGetKernelInfoResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbg_get_kernel_info_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbgGetKernelInfoResponse *
       dbg_get_kernel_info_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbgGetKernelInfoResponse *)
     protobuf_c_message_unpack (&dbg_get_kernel_info_response__descriptor,
                                allocator, len, data);
}
void   dbg_get_kernel_info_response__free_unpacked
                     (DbgGetKernelInfoResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbg_get_kernel_info_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbg_read_kernel_memory_request__init
                     (DbgReadKernelMemoryRequest         *message)
{
  static const DbgReadKernelMemoryRequest init_value = DBG_READ_KERNEL_MEMORY_REQUEST__INIT;
  *message = init_value;
}
size_t dbg_read_kernel_memory_request__get_packed_size
                     (const DbgReadKernelMemoryRequest *message)
{
  assert(message->base.descriptor == &dbg_read_kernel_memory_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbg_read_kernel_memory_request__pack
                     (const DbgReadKernelMemoryRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbg_read_kernel_memory_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbg_read_kernel_memory_request__pack_to_buffer
                     (const DbgReadKernelMemoryRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbg_read_kernel_memory_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbgReadKernelMemoryRequest *
       dbg_read_kernel_memory_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbgReadKernelMemoryRequest *)
     protobuf_c_message_unpack (&dbg_read_kernel_memory_request__descriptor,
                                allocator, len, data);
}
void   dbg_read_kernel_memory_request__free_unpacked
                     (DbgReadKernelMemoryRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbg_read_kernel_memory_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbg_read_kernel_memory_response__init
                     (DbgReadKernelMemoryResponse         *message)
{
  static const DbgReadKernelMemoryResponse init_value = DBG_READ_KERNEL_MEMORY_RESPONSE__INIT;
  *message = init_value;
}
size_t dbg_read_kernel_memory_response__get_packed_size
                     (const DbgReadKernelMemoryResponse *message)
{
  assert(message->base.descriptor == &dbg_read_kernel_memory_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbg_read_kernel_memory_response__pack
                     (const DbgReadKernelMemoryResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbg_read_kernel_memory_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbg_read_kernel_memory_response__pack_to_buffer
                     (const DbgReadKernelMemoryResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbg_read_kernel_memory_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbgReadKernelMemoryResponse *
       dbg_read_kernel_memory_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbgReadKernelMemoryResponse *)
     protobuf_c_message_unpack (&dbg_read_kernel_memory_response__descriptor,
                                allocator, len, data);
}
void   dbg_read_kernel_memory_response__free_unpacked
                     (DbgReadKernelMemoryResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbg_read_kernel_memory_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbg_write_kernel_memory_request__init
                     (DbgWriteKernelMemoryRequest         *message)
{
  static const DbgWriteKernelMemoryRequest init_value = DBG_WRITE_KERNEL_MEMORY_REQUEST__INIT;
  *message = init_value;
}
size_t dbg_write_kernel_memory_request__get_packed_size
                     (const DbgWriteKernelMemoryRequest *message)
{
  assert(message->base.descriptor == &dbg_write_kernel_memory_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbg_write_kernel_memory_request__pack
                     (const DbgWriteKernelMemoryRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbg_write_kernel_memory_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbg_write_kernel_memory_request__pack_to_buffer
                     (const DbgWriteKernelMemoryRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbg_write_kernel_memory_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbgWriteKernelMemoryRequest *
       dbg_write_kernel_memory_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbgWriteKernelMemoryRequest *)
     protobuf_c_message_unpack (&dbg_write_kernel_memory_request__descriptor,
                                allocator, len, data);
}
void   dbg_write_kernel_memory_request__free_unpacked
                     (DbgWriteKernelMemoryRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbg_write_kernel_memory_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbg_command_request__init
                     (DbgCommandRequest         *message)
{
  static const DbgCommandRequest init_value = DBG_COMMAND_REQUEST__INIT;
  *message = init_value;
}
size_t dbg_command_request__get_packed_size
                     (const DbgCommandRequest *message)
{
  assert(message->base.descriptor == &dbg_command_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbg_command_request__pack
                     (const DbgCommandRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbg_command_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbg_command_request__pack_to_buffer
                     (const DbgCommandRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbg_command_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbgCommandRequest *
       dbg_command_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbgCommandRequest *)
     protobuf_c_message_unpack (&dbg_command_request__descriptor,
                                allocator, len, data);
}
void   dbg_command_request__free_unpacked
                     (DbgCommandRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbg_command_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor dbg_get_process_list_response__field_descriptors[1] =
{
  {
    "processes",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DbgGetProcessListResponse, n_processes),
    offsetof(DbgGetProcessListResponse, processes),
    &dbg_process_limited__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbg_get_process_list_response__field_indices_by_name[] = {
  0,   /* field[0] = processes */
};
static const ProtobufCIntRange dbg_get_process_list_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dbg_get_process_list_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DbgGetProcessListResponse",
  "DbgGetProcessListResponse",
  "DbgGetProcessListResponse",
  "",
  sizeof(DbgGetProcessListResponse),
  1,
  dbg_get_process_list_response__field_descriptors,
  dbg_get_process_list_response__field_indices_by_name,
  1,  dbg_get_process_list_response__number_ranges,
  (ProtobufCMessageInit) dbg_get_process_list_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dbg_read_process_memory_request__field_descriptors[2] =
{
  {
    "address",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DbgReadProcessMemoryRequest, address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DbgReadProcessMemoryRequest, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbg_read_process_memory_request__field_indices_by_name[] = {
  0,   /* field[0] = address */
  1,   /* field[1] = size */
};
static const ProtobufCIntRange dbg_read_process_memory_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor dbg_read_process_memory_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DbgReadProcessMemoryRequest",
  "DbgReadProcessMemoryRequest",
  "DbgReadProcessMemoryRequest",
  "",
  sizeof(DbgReadProcessMemoryRequest),
  2,
  dbg_read_process_memory_request__field_descriptors,
  dbg_read_process_memory_request__field_indices_by_name,
  1,  dbg_read_process_memory_request__number_ranges,
  (ProtobufCMessageInit) dbg_read_process_memory_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dbg_read_process_memory_response__field_descriptors[1] =
{
  {
    "data",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(DbgReadProcessMemoryResponse, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbg_read_process_memory_response__field_indices_by_name[] = {
  0,   /* field[0] = data */
};
static const ProtobufCIntRange dbg_read_process_memory_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dbg_read_process_memory_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DbgReadProcessMemoryResponse",
  "DbgReadProcessMemoryResponse",
  "DbgReadProcessMemoryResponse",
  "",
  sizeof(DbgReadProcessMemoryResponse),
  1,
  dbg_read_process_memory_response__field_descriptors,
  dbg_read_process_memory_response__field_indices_by_name,
  1,  dbg_read_process_memory_response__number_ranges,
  (ProtobufCMessageInit) dbg_read_process_memory_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dbg_write_process_memory_request__field_descriptors[2] =
{
  {
    "address",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DbgWriteProcessMemoryRequest, address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(DbgWriteProcessMemoryRequest, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbg_write_process_memory_request__field_indices_by_name[] = {
  0,   /* field[0] = address */
  1,   /* field[1] = data */
};
static const ProtobufCIntRange dbg_write_process_memory_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor dbg_write_process_memory_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DbgWriteProcessMemoryRequest",
  "DbgWriteProcessMemoryRequest",
  "DbgWriteProcessMemoryRequest",
  "",
  sizeof(DbgWriteProcessMemoryRequest),
  2,
  dbg_write_process_memory_request__field_descriptors,
  dbg_write_process_memory_request__field_indices_by_name,
  1,  dbg_write_process_memory_request__number_ranges,
  (ProtobufCMessageInit) dbg_write_process_memory_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dbg_protect_process_memory_request__field_descriptors[3] =
{
  {
    "address",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DbgProtectProcessMemoryRequest, address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "length",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DbgProtectProcessMemoryRequest, length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "protection",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DbgProtectProcessMemoryRequest, protection),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbg_protect_process_memory_request__field_indices_by_name[] = {
  0,   /* field[0] = address */
  1,   /* field[1] = length */
  2,   /* field[2] = protection */
};
static const ProtobufCIntRange dbg_protect_process_memory_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor dbg_protect_process_memory_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DbgProtectProcessMemoryRequest",
  "DbgProtectProcessMemoryRequest",
  "DbgProtectProcessMemoryRequest",
  "",
  sizeof(DbgProtectProcessMemoryRequest),
  3,
  dbg_protect_process_memory_request__field_descriptors,
  dbg_protect_process_memory_request__field_indices_by_name,
  1,  dbg_protect_process_memory_request__number_ranges,
  (ProtobufCMessageInit) dbg_protect_process_memory_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define dbg_scan_process_memory_request__field_descriptors NULL
#define dbg_scan_process_memory_request__field_indices_by_name NULL
#define dbg_scan_process_memory_request__number_ranges NULL
const ProtobufCMessageDescriptor dbg_scan_process_memory_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DbgScanProcessMemoryRequest",
  "DbgScanProcessMemoryRequest",
  "DbgScanProcessMemoryRequest",
  "",
  sizeof(DbgScanProcessMemoryRequest),
  0,
  dbg_scan_process_memory_request__field_descriptors,
  dbg_scan_process_memory_request__field_indices_by_name,
  0,  dbg_scan_process_memory_request__number_ranges,
  (ProtobufCMessageInit) dbg_scan_process_memory_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dbg_get_process_info_request__field_descriptors[1] =
{
  {
    "processId",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DbgGetProcessInfoRequest, processid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbg_get_process_info_request__field_indices_by_name[] = {
  0,   /* field[0] = processId */
};
static const ProtobufCIntRange dbg_get_process_info_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dbg_get_process_info_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DbgGetProcessInfoRequest",
  "DbgGetProcessInfoRequest",
  "DbgGetProcessInfoRequest",
  "",
  sizeof(DbgGetProcessInfoRequest),
  1,
  dbg_get_process_info_request__field_descriptors,
  dbg_get_process_info_request__field_indices_by_name,
  1,  dbg_get_process_info_request__number_ranges,
  (ProtobufCMessageInit) dbg_get_process_info_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dbg_allocate_process_memory_request__field_descriptors[1] =
{
  {
    "size",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DbgAllocateProcessMemoryRequest, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbg_allocate_process_memory_request__field_indices_by_name[] = {
  0,   /* field[0] = size */
};
static const ProtobufCIntRange dbg_allocate_process_memory_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dbg_allocate_process_memory_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DbgAllocateProcessMemoryRequest",
  "DbgAllocateProcessMemoryRequest",
  "DbgAllocateProcessMemoryRequest",
  "",
  sizeof(DbgAllocateProcessMemoryRequest),
  1,
  dbg_allocate_process_memory_request__field_descriptors,
  dbg_allocate_process_memory_request__field_indices_by_name,
  1,  dbg_allocate_process_memory_request__number_ranges,
  (ProtobufCMessageInit) dbg_allocate_process_memory_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dbg_allocate_process_memory_response__field_descriptors[2] =
{
  {
    "address",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DbgAllocateProcessMemoryResponse, address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DbgAllocateProcessMemoryResponse, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbg_allocate_process_memory_response__field_indices_by_name[] = {
  0,   /* field[0] = address */
  1,   /* field[1] = size */
};
static const ProtobufCIntRange dbg_allocate_process_memory_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor dbg_allocate_process_memory_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DbgAllocateProcessMemoryResponse",
  "DbgAllocateProcessMemoryResponse",
  "DbgAllocateProcessMemoryResponse",
  "",
  sizeof(DbgAllocateProcessMemoryResponse),
  2,
  dbg_allocate_process_memory_response__field_descriptors,
  dbg_allocate_process_memory_response__field_indices_by_name,
  1,  dbg_allocate_process_memory_response__number_ranges,
  (ProtobufCMessageInit) dbg_allocate_process_memory_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dbg_free_process_memory_request__field_descriptors[2] =
{
  {
    "address",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DbgFreeProcessMemoryRequest, address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DbgFreeProcessMemoryRequest, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbg_free_process_memory_request__field_indices_by_name[] = {
  0,   /* field[0] = address */
  1,   /* field[1] = size */
};
static const ProtobufCIntRange dbg_free_process_memory_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor dbg_free_process_memory_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DbgFreeProcessMemoryRequest",
  "DbgFreeProcessMemoryRequest",
  "DbgFreeProcessMemoryRequest",
  "",
  sizeof(DbgFreeProcessMemoryRequest),
  2,
  dbg_free_process_memory_request__field_descriptors,
  dbg_free_process_memory_request__field_indices_by_name,
  1,  dbg_free_process_memory_request__number_ranges,
  (ProtobufCMessageInit) dbg_free_process_memory_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dbg_get_process_maps_request__field_descriptors[1] =
{
  {
    "processId",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DbgGetProcessMapsRequest, processid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbg_get_process_maps_request__field_indices_by_name[] = {
  0,   /* field[0] = processId */
};
static const ProtobufCIntRange dbg_get_process_maps_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dbg_get_process_maps_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DbgGetProcessMapsRequest",
  "DbgGetProcessMapsRequest",
  "DbgGetProcessMapsRequest",
  "",
  sizeof(DbgGetProcessMapsRequest),
  1,
  dbg_get_process_maps_request__field_descriptors,
  dbg_get_process_maps_request__field_indices_by_name,
  1,  dbg_get_process_maps_request__number_ranges,
  (ProtobufCMessageInit) dbg_get_process_maps_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dbg_attach_request__field_descriptors[1] =
{
  {
    "processId",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DbgAttachRequest, processid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbg_attach_request__field_indices_by_name[] = {
  0,   /* field[0] = processId */
};
static const ProtobufCIntRange dbg_attach_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dbg_attach_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DbgAttachRequest",
  "DbgAttachRequest",
  "DbgAttachRequest",
  "",
  sizeof(DbgAttachRequest),
  1,
  dbg_attach_request__field_descriptors,
  dbg_attach_request__field_indices_by_name,
  1,  dbg_attach_request__number_ranges,
  (ProtobufCMessageInit) dbg_attach_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dbg_detach_request__field_descriptors[1] =
{
  {
    "force",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(DbgDetachRequest, force),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbg_detach_request__field_indices_by_name[] = {
  0,   /* field[0] = force */
};
static const ProtobufCIntRange dbg_detach_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dbg_detach_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DbgDetachRequest",
  "DbgDetachRequest",
  "DbgDetachRequest",
  "",
  sizeof(DbgDetachRequest),
  1,
  dbg_detach_request__field_descriptors,
  dbg_detach_request__field_indices_by_name,
  1,  dbg_detach_request__number_ranges,
  (ProtobufCMessageInit) dbg_detach_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dbg_breakpoint_request__field_descriptors[4] =
{
  {
    "enabled",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(DbgBreakpointRequest, enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DbgBreakpointRequest, address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "original",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DbgBreakpointRequest, original),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "breakpointType",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(DbgBreakpointRequest, breakpointtype),
    &dbg_breakpoint_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbg_breakpoint_request__field_indices_by_name[] = {
  1,   /* field[1] = address */
  3,   /* field[3] = breakpointType */
  0,   /* field[0] = enabled */
  2,   /* field[2] = original */
};
static const ProtobufCIntRange dbg_breakpoint_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor dbg_breakpoint_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DbgBreakpointRequest",
  "DbgBreakpointRequest",
  "DbgBreakpointRequest",
  "",
  sizeof(DbgBreakpointRequest),
  4,
  dbg_breakpoint_request__field_descriptors,
  dbg_breakpoint_request__field_indices_by_name,
  1,  dbg_breakpoint_request__number_ranges,
  (ProtobufCMessageInit) dbg_breakpoint_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dbg_breakpoint_response__field_descriptors[1] =
{
  {
    "breakpointHandle",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DbgBreakpointResponse, breakpointhandle),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbg_breakpoint_response__field_indices_by_name[] = {
  0,   /* field[0] = breakpointHandle */
};
static const ProtobufCIntRange dbg_breakpoint_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dbg_breakpoint_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DbgBreakpointResponse",
  "DbgBreakpointResponse",
  "DbgBreakpointResponse",
  "",
  sizeof(DbgBreakpointResponse),
  1,
  dbg_breakpoint_response__field_descriptors,
  dbg_breakpoint_response__field_indices_by_name,
  1,  dbg_breakpoint_response__number_ranges,
  (ProtobufCMessageInit) dbg_breakpoint_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dbg_watchpoint_request__field_descriptors[4] =
{
  {
    "enabled",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(DbgWatchpointRequest, enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DbgWatchpointRequest, address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "breakpointType",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DbgWatchpointRequest, breakpointtype),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "length",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DbgWatchpointRequest, length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbg_watchpoint_request__field_indices_by_name[] = {
  1,   /* field[1] = address */
  2,   /* field[2] = breakpointType */
  0,   /* field[0] = enabled */
  3,   /* field[3] = length */
};
static const ProtobufCIntRange dbg_watchpoint_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor dbg_watchpoint_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DbgWatchpointRequest",
  "DbgWatchpointRequest",
  "DbgWatchpointRequest",
  "",
  sizeof(DbgWatchpointRequest),
  4,
  dbg_watchpoint_request__field_descriptors,
  dbg_watchpoint_request__field_indices_by_name,
  1,  dbg_watchpoint_request__number_ranges,
  (ProtobufCMessageInit) dbg_watchpoint_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dbg_watchpoint_response__field_descriptors[1] =
{
  {
    "watchpointHandle",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DbgWatchpointResponse, watchpointhandle),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbg_watchpoint_response__field_indices_by_name[] = {
  0,   /* field[0] = watchpointHandle */
};
static const ProtobufCIntRange dbg_watchpoint_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dbg_watchpoint_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DbgWatchpointResponse",
  "DbgWatchpointResponse",
  "DbgWatchpointResponse",
  "",
  sizeof(DbgWatchpointResponse),
  1,
  dbg_watchpoint_response__field_descriptors,
  dbg_watchpoint_response__field_indices_by_name,
  1,  dbg_watchpoint_response__number_ranges,
  (ProtobufCMessageInit) dbg_watchpoint_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dbg_get_process_threads_request__field_descriptors[1] =
{
  {
    "processId",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DbgGetProcessThreadsRequest, processid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbg_get_process_threads_request__field_indices_by_name[] = {
  0,   /* field[0] = processId */
};
static const ProtobufCIntRange dbg_get_process_threads_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dbg_get_process_threads_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DbgGetProcessThreadsRequest",
  "DbgGetProcessThreadsRequest",
  "DbgGetProcessThreadsRequest",
  "",
  sizeof(DbgGetProcessThreadsRequest),
  1,
  dbg_get_process_threads_request__field_descriptors,
  dbg_get_process_threads_request__field_indices_by_name,
  1,  dbg_get_process_threads_request__number_ranges,
  (ProtobufCMessageInit) dbg_get_process_threads_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dbg_get_process_threads_response__field_descriptors[1] =
{
  {
    "threads",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DbgGetProcessThreadsResponse, n_threads),
    offsetof(DbgGetProcessThreadsResponse, threads),
    &dbg_thread_limited__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbg_get_process_threads_response__field_indices_by_name[] = {
  0,   /* field[0] = threads */
};
static const ProtobufCIntRange dbg_get_process_threads_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dbg_get_process_threads_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DbgGetProcessThreadsResponse",
  "DbgGetProcessThreadsResponse",
  "DbgGetProcessThreadsResponse",
  "",
  sizeof(DbgGetProcessThreadsResponse),
  1,
  dbg_get_process_threads_response__field_descriptors,
  dbg_get_process_threads_response__field_indices_by_name,
  1,  dbg_get_process_threads_response__number_ranges,
  (ProtobufCMessageInit) dbg_get_process_threads_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dbg_signal_process_request__field_descriptors[1] =
{
  {
    "signal",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DbgSignalProcessRequest, signal),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbg_signal_process_request__field_indices_by_name[] = {
  0,   /* field[0] = signal */
};
static const ProtobufCIntRange dbg_signal_process_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dbg_signal_process_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DbgSignalProcessRequest",
  "DbgSignalProcessRequest",
  "DbgSignalProcessRequest",
  "",
  sizeof(DbgSignalProcessRequest),
  1,
  dbg_signal_process_request__field_descriptors,
  dbg_signal_process_request__field_indices_by_name,
  1,  dbg_signal_process_request__number_ranges,
  (ProtobufCMessageInit) dbg_signal_process_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dbg_get_registers_request__field_descriptors[1] =
{
  {
    "threadId",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DbgGetRegistersRequest, threadid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbg_get_registers_request__field_indices_by_name[] = {
  0,   /* field[0] = threadId */
};
static const ProtobufCIntRange dbg_get_registers_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dbg_get_registers_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DbgGetRegistersRequest",
  "DbgGetRegistersRequest",
  "DbgGetRegistersRequest",
  "",
  sizeof(DbgGetRegistersRequest),
  1,
  dbg_get_registers_request__field_descriptors,
  dbg_get_registers_request__field_indices_by_name,
  1,  dbg_get_registers_request__number_ranges,
  (ProtobufCMessageInit) dbg_get_registers_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dbg_get_registers_response__field_descriptors[3] =
{
  {
    "gpRegisters",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DbgGetRegistersResponse, gpregisters),
    &dbg_gp_registers__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fpRegisters",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DbgGetRegistersResponse, fpregisters),
    &dbg_fp_registers__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dbRegisters",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DbgGetRegistersResponse, dbregisters),
    &dbg_db_registers__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbg_get_registers_response__field_indices_by_name[] = {
  2,   /* field[2] = dbRegisters */
  1,   /* field[1] = fpRegisters */
  0,   /* field[0] = gpRegisters */
};
static const ProtobufCIntRange dbg_get_registers_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor dbg_get_registers_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DbgGetRegistersResponse",
  "DbgGetRegistersResponse",
  "DbgGetRegistersResponse",
  "",
  sizeof(DbgGetRegistersResponse),
  3,
  dbg_get_registers_response__field_descriptors,
  dbg_get_registers_response__field_indices_by_name,
  1,  dbg_get_registers_response__number_ranges,
  (ProtobufCMessageInit) dbg_get_registers_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dbg_set_registers_request__field_descriptors[4] =
{
  {
    "threadId",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DbgSetRegistersRequest, threadid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gpRegisters",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DbgSetRegistersRequest, gpregisters),
    &dbg_gp_registers__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fpRegisters",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DbgSetRegistersRequest, fpregisters),
    &dbg_fp_registers__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dbRegisters",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DbgSetRegistersRequest, dbregisters),
    &dbg_db_registers__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbg_set_registers_request__field_indices_by_name[] = {
  3,   /* field[3] = dbRegisters */
  2,   /* field[2] = fpRegisters */
  1,   /* field[1] = gpRegisters */
  0,   /* field[0] = threadId */
};
static const ProtobufCIntRange dbg_set_registers_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor dbg_set_registers_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DbgSetRegistersRequest",
  "DbgSetRegistersRequest",
  "DbgSetRegistersRequest",
  "",
  sizeof(DbgSetRegistersRequest),
  4,
  dbg_set_registers_request__field_descriptors,
  dbg_set_registers_request__field_indices_by_name,
  1,  dbg_set_registers_request__number_ranges,
  (ProtobufCMessageInit) dbg_set_registers_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dbg_get_thread_info_request__field_descriptors[1] =
{
  {
    "threadId",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DbgGetThreadInfoRequest, threadid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbg_get_thread_info_request__field_indices_by_name[] = {
  0,   /* field[0] = threadId */
};
static const ProtobufCIntRange dbg_get_thread_info_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dbg_get_thread_info_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DbgGetThreadInfoRequest",
  "DbgGetThreadInfoRequest",
  "DbgGetThreadInfoRequest",
  "",
  sizeof(DbgGetThreadInfoRequest),
  1,
  dbg_get_thread_info_request__field_descriptors,
  dbg_get_thread_info_request__field_indices_by_name,
  1,  dbg_get_thread_info_request__number_ranges,
  (ProtobufCMessageInit) dbg_get_thread_info_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dbg_get_kernel_info_response__field_descriptors[2] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DbgGetKernelInfoResponse, version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gloablConfigData",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(DbgGetKernelInfoResponse, gloablconfigdata),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbg_get_kernel_info_response__field_indices_by_name[] = {
  1,   /* field[1] = gloablConfigData */
  0,   /* field[0] = version */
};
static const ProtobufCIntRange dbg_get_kernel_info_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor dbg_get_kernel_info_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DbgGetKernelInfoResponse",
  "DbgGetKernelInfoResponse",
  "DbgGetKernelInfoResponse",
  "",
  sizeof(DbgGetKernelInfoResponse),
  2,
  dbg_get_kernel_info_response__field_descriptors,
  dbg_get_kernel_info_response__field_indices_by_name,
  1,  dbg_get_kernel_info_response__number_ranges,
  (ProtobufCMessageInit) dbg_get_kernel_info_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dbg_read_kernel_memory_request__field_descriptors[2] =
{
  {
    "address",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DbgReadKernelMemoryRequest, address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DbgReadKernelMemoryRequest, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbg_read_kernel_memory_request__field_indices_by_name[] = {
  0,   /* field[0] = address */
  1,   /* field[1] = size */
};
static const ProtobufCIntRange dbg_read_kernel_memory_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor dbg_read_kernel_memory_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DbgReadKernelMemoryRequest",
  "DbgReadKernelMemoryRequest",
  "DbgReadKernelMemoryRequest",
  "",
  sizeof(DbgReadKernelMemoryRequest),
  2,
  dbg_read_kernel_memory_request__field_descriptors,
  dbg_read_kernel_memory_request__field_indices_by_name,
  1,  dbg_read_kernel_memory_request__number_ranges,
  (ProtobufCMessageInit) dbg_read_kernel_memory_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dbg_read_kernel_memory_response__field_descriptors[1] =
{
  {
    "data",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(DbgReadKernelMemoryResponse, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbg_read_kernel_memory_response__field_indices_by_name[] = {
  0,   /* field[0] = data */
};
static const ProtobufCIntRange dbg_read_kernel_memory_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dbg_read_kernel_memory_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DbgReadKernelMemoryResponse",
  "DbgReadKernelMemoryResponse",
  "DbgReadKernelMemoryResponse",
  "",
  sizeof(DbgReadKernelMemoryResponse),
  1,
  dbg_read_kernel_memory_response__field_descriptors,
  dbg_read_kernel_memory_response__field_indices_by_name,
  1,  dbg_read_kernel_memory_response__number_ranges,
  (ProtobufCMessageInit) dbg_read_kernel_memory_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dbg_write_kernel_memory_request__field_descriptors[2] =
{
  {
    "address",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DbgWriteKernelMemoryRequest, address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(DbgWriteKernelMemoryRequest, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbg_write_kernel_memory_request__field_indices_by_name[] = {
  0,   /* field[0] = address */
  1,   /* field[1] = data */
};
static const ProtobufCIntRange dbg_write_kernel_memory_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor dbg_write_kernel_memory_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DbgWriteKernelMemoryRequest",
  "DbgWriteKernelMemoryRequest",
  "DbgWriteKernelMemoryRequest",
  "",
  sizeof(DbgWriteKernelMemoryRequest),
  2,
  dbg_write_kernel_memory_request__field_descriptors,
  dbg_write_kernel_memory_request__field_indices_by_name,
  1,  dbg_write_kernel_memory_request__number_ranges,
  (ProtobufCMessageInit) dbg_write_kernel_memory_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue dbg_command_request__dbg_commands__enum_values_by_number[6] =
{
  { "DBG_NONE", "DBG_COMMAND_REQUEST__DBG_COMMANDS__DBG_NONE", 0 },
  { "DBG_REBOOT", "DBG_COMMAND_REQUEST__DBG_COMMANDS__DBG_REBOOT", 1 },
  { "DBG_SHUTDOWN", "DBG_COMMAND_REQUEST__DBG_COMMANDS__DBG_SHUTDOWN", 2 },
  { "DBG_PRINT", "DBG_COMMAND_REQUEST__DBG_COMMANDS__DBG_PRINT", 3 },
  { "DBG_NOTIFY", "DBG_COMMAND_REQUEST__DBG_COMMANDS__DBG_NOTIFY", 4 },
  { "DBG_INFO", "DBG_COMMAND_REQUEST__DBG_COMMANDS__DBG_INFO", 5 },
};
static const ProtobufCIntRange dbg_command_request__dbg_commands__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex dbg_command_request__dbg_commands__enum_values_by_name[6] =
{
  { "DBG_INFO", 5 },
  { "DBG_NONE", 0 },
  { "DBG_NOTIFY", 4 },
  { "DBG_PRINT", 3 },
  { "DBG_REBOOT", 1 },
  { "DBG_SHUTDOWN", 2 },
};
const ProtobufCEnumDescriptor dbg_command_request__dbg_commands__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "DbgCommandRequest.DbgCommands",
  "DbgCommands",
  "DbgCommandRequest__DbgCommands",
  "",
  6,
  dbg_command_request__dbg_commands__enum_values_by_number,
  6,
  dbg_command_request__dbg_commands__enum_values_by_name,
  1,
  dbg_command_request__dbg_commands__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor dbg_command_request__field_descriptors[1] =
{
  {
    "command",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(DbgCommandRequest, command),
    &dbg_command_request__dbg_commands__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbg_command_request__field_indices_by_name[] = {
  0,   /* field[0] = command */
};
static const ProtobufCIntRange dbg_command_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dbg_command_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DbgCommandRequest",
  "DbgCommandRequest",
  "DbgCommandRequest",
  "",
  sizeof(DbgCommandRequest),
  1,
  dbg_command_request__field_descriptors,
  dbg_command_request__field_indices_by_name,
  1,  dbg_command_request__number_ranges,
  (ProtobufCMessageInit) dbg_command_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue dbg_breakpoint_type__enum_values_by_number[3] =
{
  { "BP_NONE", "DBG_BREAKPOINT_TYPE__BP_NONE", 0 },
  { "BP_SOFTWARE", "DBG_BREAKPOINT_TYPE__BP_SOFTWARE", 1 },
  { "BP_HARDWARE", "DBG_BREAKPOINT_TYPE__BP_HARDWARE", 2 },
};
static const ProtobufCIntRange dbg_breakpoint_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex dbg_breakpoint_type__enum_values_by_name[3] =
{
  { "BP_HARDWARE", 2 },
  { "BP_NONE", 0 },
  { "BP_SOFTWARE", 1 },
};
const ProtobufCEnumDescriptor dbg_breakpoint_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "DbgBreakpointType",
  "DbgBreakpointType",
  "DbgBreakpointType",
  "",
  3,
  dbg_breakpoint_type__enum_values_by_number,
  3,
  dbg_breakpoint_type__enum_values_by_name,
  1,
  dbg_breakpoint_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
