name: C/C++ CI

on: [push]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: 13
        platform: x64
    - uses: actions/checkout@v1
    - name: Install Pre-Reqs
      run: sudo apt update && sudo apt install lld
    - name: Download and install OOSDK
      run: mkdir /home/runner/toolchain && pushd /home/runner/toolchain && wget https://github.com/OpenOrbis/OpenOrbis-PS4-Toolchain/releases/download/v0.5.2/v0.5.2.tar.gz && tar -zxvf v0.5.2.tar.gz && mv OpenOrbis/PS4Toolchain/* /home/runner/toolchain && rm -rf OpenOrbis && export OO_PS4_TOOLCHAIN=/home/runner/toolchain && echo "OO_PS4_TOOLCHAIN=/home/runner/toolchain" >> $GITHUB_ENV && popd
    #- name: configure176
    #  run: export MIRA_PLATFORM=MIRA_PLATFORM_ORBIS_BSD_176 && mkdir build176 && cd build176 && cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER=clang-13 -DCMAKE_CXX_COMPILER=clang++-13 -DMIRA_PLATFORM=MIRA_PLATFORM_ORBIS_BSD_176 -G "Unix Makefiles" .. && cd ..
    #- name: configure405
    #  run: mkdir build405 && cd build405 && cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER=clang-13 -DCMAKE_CXX_COMPILER=clang++-13 -DMIRA_PLATFORM=MIRA_PLATFORM_ORBIS_BSD_405 -G "Unix Makefiles" .. && cd .. 
    #- name: configure455
    #  run: mkdir build455 && cd build455 && cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER=clang-13 -DCMAKE_CXX_COMPILER=clang++-13 -DMIRA_PLATFORM=MIRA_PLATFORM_ORBIS_BSD_455 -G "Unix Makefiles" .. && cd .. 
    #- name: configure474    
    #  run: mkdir build474 && cd build474 && cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER=clang-13 -DCMAKE_CXX_COMPILER=clang++-13 -DMIRA_PLATFORM=MIRA_PLATFORM_ORBIS_BSD_474 -G "Unix Makefiles" .. && cd .. 
    #- name: configure501
    #  run: mkdir build501 && cd build501 && cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER=clang-13 -DCMAKE_CXX_COMPILER=clang++-13 -DMIRA_PLATFORM=MIRA_PLATFORM_ORBIS_BSD_501 -G "Unix Makefiles" .. && cd .. 
    #- name: configure505
    #  run: mkdir build505 && cd build505 && cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER=clang-13 -DCMAKE_CXX_COMPILER=clang++-13 -DMIRA_PLATFORM=MIRA_PLATFORM_ORBIS_BSD_505 -G "Unix Makefiles" .. && cd .. 
    #- name: configure620
    #  run: mkdir build620 && cd build620 && cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER=clang-13 -DCMAKE_CXX_COMPILER=clang++-13 -DMIRA_PLATFORM=MIRA_PLATFORM_ORBIS_BSD_620 -G "Unix Makefiles" .. && cd .. 
    #- name: configure650
    #  run: mkdir build650 && cd build650 && cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER=clang-13 -DCMAKE_CXX_COMPILER=clang++-13 -DMIRA_PLATFORM=MIRA_PLATFORM_ORBIS_BSD_650 -G "Unix Makefiles" .. && cd .. 
    - name: configure672
      run: mkdir build672 && cd build672 && cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER=clang-13 -DCMAKE_CXX_COMPILER=clang++-13 -DMIRA_PLATFORM=MIRA_PLATFORM_ORBIS_BSD_672 -G "Unix Makefiles" .. && cd .. 
    #- name: configure755
    #  run: mkdir build755 && cd build755 && cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER=clang-13 -DCMAKE_CXX_COMPILER=clang++-13 -DMIRA_PLATFORM=MIRA_PLATFORM_ORBIS_BSD_755 -G "Unix Makefiles" .. && cd ..
    #- name: build176
    #  run: cmake --build build176
    #- name: build405
    #  run: cmake --build build405
    #- name: build455
    #  run: cmake --build build455
    #- name: build474
    #  run: cmake --build build474
    #- name: build501
    #  run: cmake --build build501
    #- name: build505
    #  run: cmake --build build505
    #- name: build620
    #  run: cmake --build build620
    #- name: build650
    #  run: cmake --build build650
    - name: build672
      run: cmake --build build672
    #- name: build755
    #  run: cmake --build build755
    - name: upload mira binaries
      uses: actions/upload-artifact@v2
      with:
        name: Binaries
        path: |
          build176/loader/loader.bin
          build405/loader/loader.bin
          build455/loader/loader.bin
          build474/loader/loader.bin
          build501/loader/loader.bin
          build505/loader/loader.bin
          build620/loader/loader.bin
          build650/loader/loader.bin
          build672/loader/loader.bin
          build672/example_trainer/example_trainer.prx
          build672/tests/tests.EBOOT.BIN
          build672/daemon/daemon.prx
          build672/mira_module/mira_module.prx
          build755/loader/loader.bin
          
