name: C/C++ CI

on: [push]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: 13
        platform: x64
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir build && cd build && cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER=clang-13 -DCMAKE_CXX_COMPILER=clang++-13 -G "Unix Makefiles" ..
    - name: build
      run: cmake --build build

    - name: upload loader
      uses: actions/upload-artifact@v2
      with:
        name: loader.bin
        path: build/loader/loader.bin