name: Orbis620

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        # Checkout the repository
      - uses: actions/checkout@v2
        # Install required stuff needed to build Mira
      - name: preinstall
        run: wget -q -O - https://files.viva64.com/etc/pubkey.txt | sudo apt-key add -; sudo wget -O /etc/apt/sources.list.d/viva64.list https://files.viva64.com/etc/viva64.list; sudo apt-get update; sudo apt install build-essential git clang lldb clang-tidy clang-tools cppcheck pvs-studio
        # Handle loader crap
      - name: create loader directories
        run: cd loader; MIRA_PLATFORM=MIRA_PLATFORM_ORBIS_BSD_620 make create
      - name: clean loader
        run: cd loader; MIRA_PLATFORM=MIRA_PLATFORM_ORBIS_BSD_620 make clean
      - name: create mira directories
        run: cd kernel; MIRA_PLATFORM=MIRA_PLATFORM_ORBIS_BSD_620 make create
      - name: clean mira
        run: cd kernel; MIRA_PLATFORM=MIRA_PLATFORM_ORBIS_BSD_620 make clean
        # 6.20 Support
      - name: make 6.20 loader
        run: cd loader; MIRA_PLATFORM=MIRA_PLATFORM_ORBIS_BSD_620 MIRA_CHECKS=TRUE pvs-studio-analyzer trace -- make
      - name: generate 6.20 loader pvs report
        run: cd loader; pvs-studio-analyzer analyze -e ../external/ -o project.log; plog-converter -a GA:1,2 -t fullhtml -o pvs-html project.log; plog-converter -a GA:1,2 -t tasklist -o report.tasks project.log
      - name: make 6.20 elf
        run: cd kernel; MIRA_PLATFORM=MIRA_PLATFORM_ORBIS_BSD_620 ADD_GIT_HASH=TRUE MIRA_CHECKS=TRUE pvs-studio-analyzer trace -- make
      - name: generate 6.20 elf pvs report
        run: cd kernel; pvs-studio-analyzer analyze -e ../external/ -e src/External/ -e src/Messaging/Rpc/rpc.pb-c.c -e src/Plugins/FileManager/filemanager.pb-c.c -o project.log; plog-converter -a GA:1,2 -t fullhtml -o pvs-html project.log; plog-converter -a GA:1,2 -t tasklist -o report.tasks project.log
      - name: Upload 6.20 loader
        uses: actions/upload-artifact@v2
        with:
          name: MiraLoader_Orbis_MIRA_PLATFORM_ORBIS_BSD_620.bin
          path: loader/build/MiraLoader_Orbis_MIRA_PLATFORM_ORBIS_BSD_620.bin
      - name: Upload 6.20 loader pvs report
        uses: actions/upload-artifact@v2
        with:
          name: MiraLoader_PVS_Report
          path: |
            loader/report.tasks
            loader/pvs-html/
      - name: Upload 6.20 elf
        uses: actions/upload-artifact@v2
        with:
          name: Mira_Orbis_MIRA_PLATFORM_ORBIS_BSD_620.elf
          path: kernel/build/Mira_Orbis_MIRA_PLATFORM_ORBIS_BSD_620.elf
      - name: Upload 6.20 elf pvs report
        uses: actions/upload-artifact@v2
        with:
          name: Mira_PVS_Report
          path: |
            kernel/report.tasks
            kernel/pvs-html/
