name: Orbis702

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        # Checkout the repository
      - uses: actions/checkout@v2
        # Install required stuff needed to build Mira
      - name: preinstall
        run: sudo apt install build-essential git clang lldb clang-tidy clang-tools cppcheck
        # Handle loader crap
      - name: create loader directories
        run: cd loader; make create
      - name: clean loader
        run: cd loader; make clean
      - name: create mira directories
        run: cd kernel; make create
      - name: clean mira
        run: cd kernel; make clean
        # 7.02 Support
      - name: make 7.02 loader
        run: cd loader; MIRA_PLATFORM=MIRA_PLATFORM_ORBIS_BSD_702 MIRA_CHECKS=TRUE make
      - name: make 7.02 elf
        run: cd kernel; MIRA_PLATFORM=MIRA_PLATFORM_ORBIS_BSD_702 ADD_GIT_HASH=TRUE MIRA_CHECKS=TRUE make
      - name: Upload 7.02 loader
        uses: actions/upload-artifact@v2
        with:
          name: MiraLoader_Orbis_MIRA_PLATFORM_ORBIS_BSD_702.bin
          path: loader/build/MiraLoader_Orbis_MIRA_PLATFORM_ORBIS_BSD_702.bin
      - name: Upload 7.02 elf
        uses: actions/upload-artifact@v2
        with:
          name: Mira_Orbis_MIRA_PLATFORM_ORBIS_BSD_702.elf
          path: kernel/build/Mira_Orbis_MIRA_PLATFORM_ORBIS_BSD_702.elf
